// Generated by @treeui/tokens. DO NOT EDIT.
// Regenerate with: pnpm codegen:native
// Colour contract version: 1.0

// rustfmt is asked to leave this file alone on purpose. Nobody reads it to
// learn the codebase and nobody edits it, so its line breaks carry no
// information — but if the formatter rewrapped it, `cargo fmt` and
// `pnpm codegen:native --check` would each report the other's output as
// wrong, forever.
#![cfg_attr(rustfmt, rustfmt::skip)]

//! The TreeUI token layer, resolved for Rust.
//!
//! Lengths and type sizes are logical pixels, taken from the CSS model at its
//! authored root size of 16px — one CSS pixel is one egui point. Nothing
//! here depends on a GUI crate, so this module also serves a consumer that only
//! wants the palette.

// The hand-written support types live in the crate root, so the generated
// half holds nothing but values. Only the types the palette itself needs are
// imported here; a group whose values need one imports it in its own module.
use crate::{Color, ColorMode, Gradient, GradientStop, ShadowLayer};

/// The colour contract this file was generated against.
pub const CONTRACT_VERSION: &str = "1.0";

/// The CSS root font size the lengths below were resolved against.
pub const ROOT_FONT_SIZE_PX: f32 = 16.0;

/// Font stacks, most preferred family first.
pub mod font_family {
    /// `--tree-font-family-sans`
    pub const SANS: &[&str] = &["Google Sans Flex", "Segoe UI", "sans-serif"];
    /// `--tree-font-family-mono`
    pub const MONO: &[&str] = &["Google Sans Code", "SFMono-Regular", "monospace"];
}

/// Type scale. These follow the reader’s text-size setting — scalable pixels, not device-independent ones.
pub mod font_size {
    /// `--tree-font-size-xs`
    pub const XS: f32 = 11.0;
    /// `--tree-font-size-sm`
    pub const SM: f32 = 13.0;
    /// `--tree-font-size-md`
    pub const MD: f32 = 15.0;
    /// `--tree-font-size-base`
    pub const BASE: f32 = 15.0;
    /// `--tree-font-size-lg`
    pub const LG: f32 = 18.0;
    /// `--tree-font-size-xl`
    pub const XL: f32 = 22.0;
    /// `--tree-font-size-2xl`
    pub const XL2: f32 = 24.0;
    /// `--tree-font-size-3xl`
    pub const XL3: f32 = 28.0;
    /// `--tree-font-size-4xl`
    pub const XL4: f32 = 36.0;
    /// `--tree-font-size-5xl`
    pub const XL5: f32 = 48.0;
}

/// CSS numeric weights, which every target maps 1:1.
pub mod font_weight {
    /// `--tree-font-weight-regular`
    pub const REGULAR: u16 = 400;
    /// `--tree-font-weight-medium`
    pub const MEDIUM: u16 = 500;
    /// `--tree-font-weight-semibold`
    pub const SEMIBOLD: u16 = 600;
    /// `--tree-font-weight-bold`
    pub const BOLD: u16 = 700;
    /// `--tree-font-weight-extrabold`
    pub const EXTRABOLD: u16 = 800;
}

/// Unitless multipliers of the font size.
pub mod line_height {
    /// `--tree-font-lineHeight-compact`
    pub const COMPACT: f32 = 1.1;
    /// `--tree-font-lineHeight-ui`
    pub const UI: f32 = 1.15;
    /// `--tree-font-lineHeight-tight`
    pub const TIGHT: f32 = 1.25;
    /// `--tree-font-lineHeight-heading`
    pub const HEADING: f32 = 1.3;
    /// `--tree-font-lineHeight-base`
    pub const BASE: f32 = 1.5;
    /// `--tree-font-lineHeight-body`
    pub const BODY: f32 = 1.6;
    /// `--tree-font-lineHeight-relaxed`
    pub const RELAXED: f32 = 1.65;
}

/// Letter spacing as a multiple of the font size (CSS `em`).
pub mod tracking {
    /// `--tree-font-tracking-tight`
    pub const TIGHT: f32 = -0.02;
    /// `--tree-font-tracking-normal`
    pub const NORMAL: f32 = 0.0;
    /// `--tree-font-tracking-wide`
    pub const WIDE: f32 = 0.08;
}

/// Spacing scale, in pixels.
pub mod space {
    /// `--tree-space-0`
    pub const S0: f32 = 0.0;
    /// `--tree-space-1`
    pub const S1: f32 = 4.0;
    /// `--tree-space-2`
    pub const S2: f32 = 8.0;
    /// `--tree-space-3`
    pub const S3: f32 = 12.0;
    /// `--tree-space-4`
    pub const S4: f32 = 16.0;
    /// `--tree-space-5`
    pub const S5: f32 = 20.0;
    /// `--tree-space-6`
    pub const S6: f32 = 24.0;
    /// `--tree-space-8`
    pub const S8: f32 = 32.0;
    /// `--tree-space-12`
    pub const S12: f32 = 48.0;
    /// `--tree-space-16`
    pub const S16: f32 = 64.0;
}

/// Corner radii, in pixels.
pub mod radius {
    /// `--tree-radius-sm`
    pub const SM: f32 = 6.0;
    /// `--tree-radius-md`
    pub const MD: f32 = 10.0;
    /// `--tree-radius-lg`
    pub const LG: f32 = 14.0;
    /// `--tree-radius-pill`
    pub const PILL: f32 = 999.0;
}

/// Control heights, in pixels — one per size step.
pub mod control_size {
    /// `--tree-size-control-sm`
    pub const SM: f32 = 32.0;
    /// `--tree-size-control-md`
    pub const MD: f32 = 40.0;
    /// `--tree-size-control-lg`
    pub const LG: f32 = 48.0;
}

/// Icon box sizes, in pixels.
pub mod icon_size {
    /// `--tree-size-icon-sm`
    pub const SM: f32 = 16.0;
    /// `--tree-size-icon-md`
    pub const MD: f32 = 20.0;
    /// `--tree-size-icon-lg`
    pub const LG: f32 = 24.0;
    /// `--tree-size-icon-xl`
    pub const XL: f32 = 32.0;
    /// `--tree-size-icon-2xl`
    pub const XL2: f32 = 48.0;
}

/// Stroke widths, in pixels.
pub mod border_width {
    /// `--tree-border-width-subtle`
    pub const SUBTLE: f32 = 1.0;
    /// `--tree-border-width-strong`
    pub const STRONG: f32 = 1.5;
}

/// Grid gutters, in pixels.
pub mod gutter {
    /// `--tree-layout-gutter-sm`
    pub const SM: f32 = 16.0;
    /// `--tree-layout-gutter-md`
    pub const MD: f32 = 24.0;
}

/// Page margins, in pixels.
pub mod margin {
    /// `--tree-layout-margin-sm`
    pub const SM: f32 = 24.0;
    /// `--tree-layout-margin-md`
    pub const MD: f32 = 32.0;
    /// `--tree-layout-margin-lg`
    pub const LG: f32 = 48.0;
}

/// The layout grid itself: its column count and its base unit.
pub mod grid {
    /// `--tree-layout-grid-base`
    pub const BASE: f32 = 8.0;
    /// `--tree-layout-grid-columns`
    pub const COLUMNS: u32 = 12;
}

/// Viewport widths, in pixels.
pub mod breakpoint {
    /// `--tree-breakpoint-sm`
    pub const SM: f32 = 640.0;
    /// `--tree-breakpoint-md`
    pub const MD: f32 = 768.0;
    /// `--tree-breakpoint-lg`
    pub const LG: f32 = 1024.0;
    /// `--tree-breakpoint-xl`
    pub const XL: f32 = 1280.0;
}

/// The one opacity the system uses, for the parts of a disabled control that carry no text.
pub mod opacity {
    /// `--tree-opacity-disabled`
    pub const DISABLED: f32 = 0.5;
}

/// Animation durations, in milliseconds.
pub mod duration {
    /// `--tree-motion-duration-fast`
    pub const FAST: u32 = 100;
    /// `--tree-motion-duration-moderate`
    pub const MODERATE: u32 = 200;
    /// `--tree-motion-duration-normal`
    pub const NORMAL: u32 = 300;
    /// `--tree-motion-duration-slow`
    pub const SLOW: u32 = 400;
    /// `--tree-motion-duration-slower`
    pub const SLOWER: u32 = 500;
}

/// Cubic-bezier timing functions, as their four control values.
pub mod easing {
    use crate::Easing;

    /// `--tree-motion-easing-standard`
    pub const STANDARD: Easing = Easing { x1: 0.2, y1: 0.0, x2: 0.0, y2: 1.0 };
    /// `--tree-motion-easing-easeOut`
    pub const EASE_OUT: Easing = Easing { x1: 0.0, y1: 0.0, x2: 0.2, y2: 1.0 };
    /// `--tree-motion-easing-easeInOut`
    pub const EASE_IN_OUT: Easing = Easing { x1: 0.4, y1: 0.0, x2: 0.2, y2: 1.0 };
    /// `--tree-motion-easing-easeIn`
    pub const EASE_IN: Easing = Easing { x1: 0.4, y1: 0.0, x2: 1.0, y2: 1.0 };
}

/// Stacking order. A retained-mode target draws in declaration order, so these are the tie-break for overlay surfaces.
pub mod z_index {
    /// `--tree-z-base`
    pub const BASE: i32 = 1;
    /// `--tree-z-dropdown`
    pub const DROPDOWN: i32 = 1000;
    /// `--tree-z-popover`
    pub const POPOVER: i32 = 1050;
    /// `--tree-z-sticky`
    pub const STICKY: i32 = 1100;
    /// `--tree-z-overlay`
    pub const OVERLAY: i32 = 1200;
    /// `--tree-z-modal`
    pub const MODAL: i32 = 1300;
    /// `--tree-z-toast`
    pub const TOAST: i32 = 1400;
}

/// Size steps, shared by most components.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Size {
    /// `"sm"`
    Sm,
    /// `"md"`
    Md,
    /// `"lg"`
    Lg,
}

impl Size {
    /// The string this member is spelled with on the web — its CSS modifier and its JS prop value.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Sm => "sm",
            Self::Md => "md",
            Self::Lg => "lg",
        }
    }
}

/// Shape scale for an action surface. Orthogonal to its tone.
///
/// `danger` is absent on purpose: it is a colour trapped in the shape scale, so it could only ever be a filled red button. Use `Solid` with `Tone::Danger`, which composes with the quiet variants too.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Variant {
    /// `"solid"`
    Solid,
    /// `"outline"`
    Outline,
    /// `"ghost"`
    Ghost,
    /// `"soft"`
    Soft,
}

impl Variant {
    /// The string this member is spelled with on the web — its CSS modifier and its JS prop value.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Solid => "solid",
            Self::Outline => "outline",
            Self::Ghost => "ghost",
            Self::Soft => "soft",
        }
    }
}

/// Surface scale for a card — not action variants. `solid` is deliberately absent.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum CardVariant {
    /// `"outline"`
    Outline,
    /// `"soft"`
    Soft,
    /// `"inset"`
    Inset,
}

impl CardVariant {
    /// The string this member is spelled with on the web — its CSS modifier and its JS prop value.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Outline => "outline",
            Self::Soft => "soft",
            Self::Inset => "inset",
        }
    }
}

/// Tone set for a component that states a status rather than offering an action. Narrower than `Tone`: no brand, no accent.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum BadgeTone {
    /// `"neutral"`
    Neutral,
    /// `"success"`
    Success,
    /// `"warning"`
    Warning,
    /// `"danger"`
    Danger,
    /// `"info"`
    Info,
}

impl BadgeTone {
    /// The string this member is spelled with on the web — its CSS modifier and its JS prop value.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Neutral => "neutral",
            Self::Success => "success",
            Self::Warning => "warning",
            Self::Danger => "danger",
            Self::Info => "info",
        }
    }
}

/// The accent axis a surface declares and its descendants inherit.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Accent {
    /// `"brand"`
    Brand,
    /// `"neutral"`
    Neutral,
    /// `"success"`
    Success,
    /// `"warning"`
    Warning,
    /// `"danger"`
    Danger,
    /// `"info"`
    Info,
}

impl Accent {
    /// The string this member is spelled with on the web — its CSS modifier and its JS prop value.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Brand => "brand",
            Self::Neutral => "neutral",
            Self::Success => "success",
            Self::Warning => "warning",
            Self::Danger => "danger",
            Self::Info => "info",
        }
    }
}

/// Inline-size scale for a form control. Controls fill their container by default.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum FieldWidth {
    /// `"xs"`
    Xs,
    /// `"sm"`
    Sm,
    /// `"md"`
    Md,
    /// `"lg"`
    Lg,
    /// `"xl"`
    Xl,
    /// `"full"`
    Full,
}

impl FieldWidth {
    /// The string this member is spelled with on the web — its CSS modifier and its JS prop value.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Xs => "xs",
            Self::Sm => "sm",
            Self::Md => "md",
            Self::Lg => "lg",
            Self::Xl => "xl",
            Self::Full => "full",
        }
    }
}

/// Placement for a tooltip, relative to its trigger.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum TooltipSide {
    /// `"top"`
    Top,
    /// `"right"`
    Right,
    /// `"bottom"`
    Bottom,
    /// `"left"`
    Left,
}

impl TooltipSide {
    /// The string this member is spelled with on the web — its CSS modifier and its JS prop value.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Top => "top",
            Self::Right => "right",
            Self::Bottom => "bottom",
            Self::Left => "left",
        }
    }
}

/// Edge a drawer enters from.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum DrawerSide {
    /// `"top"`
    Top,
    /// `"right"`
    Right,
    /// `"bottom"`
    Bottom,
    /// `"left"`
    Left,
}

impl DrawerSide {
    /// The string this member is spelled with on the web — its CSS modifier and its JS prop value.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Top => "top",
            Self::Right => "right",
            Self::Bottom => "bottom",
            Self::Left => "left",
        }
    }
}

/// Breakpoint names, paired with the `breakpoint-*` lengths.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Breakpoint {
    /// `"sm"`
    Sm,
    /// `"md"`
    Md,
    /// `"lg"`
    Lg,
    /// `"xl"`
    Xl,
}

impl Breakpoint {
    /// The string this member is spelled with on the web — its CSS modifier and its JS prop value.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Sm => "sm",
            Self::Md => "md",
            Self::Lg => "lg",
            Self::Xl => "xl",
        }
    }
}

/// One theme, fully resolved: the semantic colours a product fills in, the
/// interaction states the library derives from them, and the two groups whose
/// CSS refers to theme variables and so can only exist per theme.
///
/// Every field is required. A palette assembled by hand that omits one does not
/// compile, which is the Rust form of the contract validator.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Palette {
    /// Which of the two colour modes this palette is.
    pub mode: ColorMode,
    /// `--tree-color-bg-primary` — The page canvas, behind everything else.
    pub bg_primary: Color,
    /// `--tree-color-bg-surface` — A raised surface sitting on the canvas: card, modal, popover, table head.
    pub bg_surface: Color,
    /// `--tree-color-bg-subtle` — A recessed or quiet band inside a surface: inset card, code block, disabled field.
    pub bg_subtle: Color,
    /// `--tree-color-border-default` — Decorative edges — card outline, divider, table rule. Not a control boundary.
    pub border_default: Color,
    /// `--tree-color-border-strong` — An emphasised decorative edge, and the hover edge of a quiet control.
    pub border_strong: Color,
    /// `--tree-color-text-primary` — Body and heading ink on any bg.* surface.
    pub text_primary: Color,
    /// `--tree-color-text-muted` — Secondary ink: help text, captions, placeholders. Still passes AA.
    pub text_muted: Color,
    /// `--tree-color-text-inverse` — Ink for a surface that inverts the theme. NOT the ink for a brand fill — that is brand.contrast, which is computed per theme.
    pub text_inverse: Color,
    /// `--tree-color-shadow-rgb` — Umbra as an "r, g, b" triple. The elevation scale varies alpha over it.
    pub shadow_rgb: Color,
    /// `--tree-color-brand-primary` — The product accent: primary action fill, active nav, focus emphasis, links.
    pub brand_primary: Color,
    /// `--tree-color-brand-hover` — Hover fill for a solid brand surface. Public for compatibility; new state tokens are derived. Seeding a theme computes this for you.
    pub brand_hover: Color,
    /// `--tree-color-brand-soft` — Brand tint: soft button, selected row, badge background. Carries brand ink.
    pub brand_soft: Color,
    /// `--tree-color-brand-contrast` — Ink ON a solid brand fill. Computed per theme by whichever of black/white reads better on that accent — never hardcoded in a component.
    pub brand_contrast: Color,
    /// `--tree-color-accent-primary` — Secondary accent, for surfaces that need a second voice next to brand.
    pub accent_primary: Color,
    /// `--tree-color-accent-hover` — Hover fill for a solid secondary-accent surface.
    pub accent_hover: Color,
    /// `--tree-color-accent-soft` — Secondary-accent tint. Carries accent ink.
    pub accent_soft: Color,
    /// `--tree-color-accent-contrast` — Ink ON a solid secondary-accent fill. Computed per theme.
    pub accent_contrast: Color,
    /// `--tree-color-status-success` — Confirmed / healthy. Independent of brand — do not remap it to the accent.
    pub status_success: Color,
    /// `--tree-color-status-warning` — Needs attention, not yet broken.
    pub status_warning: Color,
    /// `--tree-color-status-error` — Failed / destructive. Also the ink for validation messages.
    pub status_error: Color,
    /// `--tree-color-status-info` — Neutral information. Ships equal to brand.primary in the default theme; a product with a non-blue accent should set this so info stays distinguishable.
    pub status_info: Color,
    /// `--tree-color-chart-1` — Categorical series 1. Fixed hue order; assign in sequence.
    pub chart_1: Color,
    /// `--tree-color-chart-2` — Categorical series 2. Fixed hue order; assign in sequence.
    pub chart_2: Color,
    /// `--tree-color-chart-3` — Categorical series 3. Fixed hue order; assign in sequence.
    pub chart_3: Color,
    /// `--tree-color-chart-4` — Categorical series 4. Fixed hue order; assign in sequence.
    pub chart_4: Color,
    /// `--tree-color-chart-5` — Categorical series 5. Fixed hue order; assign in sequence.
    pub chart_5: Color,
    /// `--tree-color-chart-6` — Categorical series 6. Fixed hue order; assign in sequence.
    pub chart_6: Color,
    /// `--tree-color-chart-7` — Categorical series 7. Fixed hue order; assign in sequence.
    pub chart_7: Color,
    /// `--tree-color-chart-8` — Categorical series 8. Fixed hue order; assign in sequence.
    pub chart_8: Color,
    /// `--tree-color-overlay` — Scrim behind a modal or drawer. Carries alpha.
    pub overlay: Color,
    /// `--tree-color-focus-ring` — The focus indicator. Carries alpha; width is --tree-focus-ring-width.
    pub focus_ring: Color,
    /// `--tree-color-border-interactive` — The boundary that identifies a form control (input, select, checkbox, radio). Must clear 3:1 on every surface — WCAG 1.4.11. Derived when omitted.
    pub border_interactive: Color,
    /// `--tree-color-brand-press` — derived by the library from the semantic layer. Read it; never set it.
    pub brand_press: Color,
    /// `--tree-color-brand-soft-hover` — derived by the library from the semantic layer. Read it; never set it.
    pub brand_soft_hover: Color,
    /// `--tree-color-brand-soft-press` — derived by the library from the semantic layer. Read it; never set it.
    pub brand_soft_press: Color,
    /// `--tree-color-brand-on-soft` — derived by the library from the semantic layer. Read it; never set it.
    pub brand_on_soft: Color,
    /// `--tree-color-brand-on-soft-hover` — derived by the library from the semantic layer. Read it; never set it.
    pub brand_on_soft_hover: Color,
    /// `--tree-color-brand-on-soft-press` — derived by the library from the semantic layer. Read it; never set it.
    pub brand_on_soft_press: Color,
    /// `--tree-color-accent-press` — derived by the library from the semantic layer. Read it; never set it.
    pub accent_press: Color,
    /// `--tree-color-accent-soft-hover` — derived by the library from the semantic layer. Read it; never set it.
    pub accent_soft_hover: Color,
    /// `--tree-color-accent-soft-press` — derived by the library from the semantic layer. Read it; never set it.
    pub accent_soft_press: Color,
    /// `--tree-color-accent-on-soft` — derived by the library from the semantic layer. Read it; never set it.
    pub accent_on_soft: Color,
    /// `--tree-color-accent-on-soft-hover` — derived by the library from the semantic layer. Read it; never set it.
    pub accent_on_soft_hover: Color,
    /// `--tree-color-accent-on-soft-press` — derived by the library from the semantic layer. Read it; never set it.
    pub accent_on_soft_press: Color,
    /// `--tree-color-status-success-hover` — derived by the library from the semantic layer. Read it; never set it.
    pub status_success_hover: Color,
    /// `--tree-color-status-success-press` — derived by the library from the semantic layer. Read it; never set it.
    pub status_success_press: Color,
    /// `--tree-color-status-success-soft` — derived by the library from the semantic layer. Read it; never set it.
    pub status_success_soft: Color,
    /// `--tree-color-status-success-soft-hover` — derived by the library from the semantic layer. Read it; never set it.
    pub status_success_soft_hover: Color,
    /// `--tree-color-status-success-border` — derived by the library from the semantic layer. Read it; never set it.
    pub status_success_border: Color,
    /// `--tree-color-status-success-contrast` — derived by the library from the semantic layer. Read it; never set it.
    pub status_success_contrast: Color,
    /// `--tree-color-status-success-on-soft` — derived by the library from the semantic layer. Read it; never set it.
    pub status_success_on_soft: Color,
    /// `--tree-color-status-success-on-soft-hover` — derived by the library from the semantic layer. Read it; never set it.
    pub status_success_on_soft_hover: Color,
    /// `--tree-color-status-warning-hover` — derived by the library from the semantic layer. Read it; never set it.
    pub status_warning_hover: Color,
    /// `--tree-color-status-warning-press` — derived by the library from the semantic layer. Read it; never set it.
    pub status_warning_press: Color,
    /// `--tree-color-status-warning-soft` — derived by the library from the semantic layer. Read it; never set it.
    pub status_warning_soft: Color,
    /// `--tree-color-status-warning-soft-hover` — derived by the library from the semantic layer. Read it; never set it.
    pub status_warning_soft_hover: Color,
    /// `--tree-color-status-warning-border` — derived by the library from the semantic layer. Read it; never set it.
    pub status_warning_border: Color,
    /// `--tree-color-status-warning-contrast` — derived by the library from the semantic layer. Read it; never set it.
    pub status_warning_contrast: Color,
    /// `--tree-color-status-warning-on-soft` — derived by the library from the semantic layer. Read it; never set it.
    pub status_warning_on_soft: Color,
    /// `--tree-color-status-warning-on-soft-hover` — derived by the library from the semantic layer. Read it; never set it.
    pub status_warning_on_soft_hover: Color,
    /// `--tree-color-status-error-hover` — derived by the library from the semantic layer. Read it; never set it.
    pub status_error_hover: Color,
    /// `--tree-color-status-error-press` — derived by the library from the semantic layer. Read it; never set it.
    pub status_error_press: Color,
    /// `--tree-color-status-error-soft` — derived by the library from the semantic layer. Read it; never set it.
    pub status_error_soft: Color,
    /// `--tree-color-status-error-soft-hover` — derived by the library from the semantic layer. Read it; never set it.
    pub status_error_soft_hover: Color,
    /// `--tree-color-status-error-border` — derived by the library from the semantic layer. Read it; never set it.
    pub status_error_border: Color,
    /// `--tree-color-status-error-contrast` — derived by the library from the semantic layer. Read it; never set it.
    pub status_error_contrast: Color,
    /// `--tree-color-status-error-on-soft` — derived by the library from the semantic layer. Read it; never set it.
    pub status_error_on_soft: Color,
    /// `--tree-color-status-error-on-soft-hover` — derived by the library from the semantic layer. Read it; never set it.
    pub status_error_on_soft_hover: Color,
    /// `--tree-color-status-info-hover` — derived by the library from the semantic layer. Read it; never set it.
    pub status_info_hover: Color,
    /// `--tree-color-status-info-press` — derived by the library from the semantic layer. Read it; never set it.
    pub status_info_press: Color,
    /// `--tree-color-status-info-soft` — derived by the library from the semantic layer. Read it; never set it.
    pub status_info_soft: Color,
    /// `--tree-color-status-info-soft-hover` — derived by the library from the semantic layer. Read it; never set it.
    pub status_info_soft_hover: Color,
    /// `--tree-color-status-info-border` — derived by the library from the semantic layer. Read it; never set it.
    pub status_info_border: Color,
    /// `--tree-color-status-info-contrast` — derived by the library from the semantic layer. Read it; never set it.
    pub status_info_contrast: Color,
    /// `--tree-color-status-info-on-soft` — derived by the library from the semantic layer. Read it; never set it.
    pub status_info_on_soft: Color,
    /// `--tree-color-status-info-on-soft-hover` — derived by the library from the semantic layer. Read it; never set it.
    pub status_info_on_soft_hover: Color,
    /// `--tree-color-state-hover-bg` — derived by the library from the semantic layer. Read it; never set it.
    pub state_hover_bg: Color,
    /// `--tree-color-state-press-bg` — derived by the library from the semantic layer. Read it; never set it.
    pub state_press_bg: Color,
    /// `--tree-color-state-selected-bg` — derived by the library from the semantic layer. Read it; never set it.
    pub state_selected_bg: Color,
    /// `--tree-color-state-selected-fg` — derived by the library from the semantic layer. Read it; never set it.
    pub state_selected_fg: Color,
    /// `--tree-color-state-selected-border` — derived by the library from the semantic layer. Read it; never set it.
    pub state_selected_border: Color,
    /// `--tree-color-state-disabled-bg` — derived by the library from the semantic layer. Read it; never set it.
    pub state_disabled_bg: Color,
    /// `--tree-color-state-disabled-fg` — derived by the library from the semantic layer. Read it; never set it.
    pub state_disabled_fg: Color,
    /// `--tree-color-state-disabled-border` — derived by the library from the semantic layer. Read it; never set it.
    pub state_disabled_border: Color,
    /// `--tree-shadow-xs` — layers in paint order, colour already composited over the theme's umbra.
    pub shadow_xs: &'static [ShadowLayer],
    /// `--tree-shadow-sm` — layers in paint order, colour already composited over the theme's umbra.
    pub shadow_sm: &'static [ShadowLayer],
    /// `--tree-shadow-md` — layers in paint order, colour already composited over the theme's umbra.
    pub shadow_md: &'static [ShadowLayer],
    /// `--tree-shadow-lg` — layers in paint order, colour already composited over the theme's umbra.
    pub shadow_lg: &'static [ShadowLayer],
    /// `--tree-shadow-xl` — layers in paint order, colour already composited over the theme's umbra.
    pub shadow_xl: &'static [ShadowLayer],
    /// `--tree-shadow-accent` — layers in paint order, colour already composited over the theme's umbra.
    pub shadow_accent: &'static [ShadowLayer],
    /// `--tree-gradient-brand`
    pub gradient_brand: Gradient,
}

/// The colour axis for an action surface, orthogonal to its variant.
///
/// The variant decides the SHAPE — filled, outlined, quiet, tinted — and the
/// tone decides which colour set that shape paints with. Splitting them is what
/// makes a quiet destructive action expressible: a single `danger` variant could
/// only ever be a filled red button.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Tone {
    /// The page's own ink rather than a hue — an action that makes no colour claim.
    Neutral,
    /// The product's primary action. The default when no tone is set.
    Brand,
    /// The secondary brand accent: branded, without competing with the primary action.
    Accent,
    /// A confirming action, or one whose outcome is a success state.
    Success,
    /// An action that warrants a second look before it is taken.
    Warning,
    /// A destructive action. It composes with every variant, so a destructive action can also be a quiet one.
    Danger,
    /// An advisory action in a neutral, informational context.
    Info,
}

/// One tone resolved against one palette.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct ToneColors {
    /// The tone's solid fill, and its ink on the quiet variants.
    pub accent: Color,
    /// The tone's solid fill, and its ink on the quiet variants.
    pub accent_hover: Color,
    /// The tone's solid fill, and its ink on the quiet variants.
    pub accent_press: Color,
    /// The tone's tint, which the `soft` variant fills with.
    pub accent_soft: Color,
    /// The tone's tint, which the `soft` variant fills with.
    pub accent_soft_hover: Color,
    /// The tone's tint, which the `soft` variant fills with.
    pub accent_soft_press: Color,
    /// Ink that clears AA on the tint. It deepens as the tint deepens, because a tint has only so much headroom.
    pub accent_on_soft: Color,
    /// The tone's solid fill, and its ink on the quiet variants.
    pub accent_on_soft_hover: Color,
    /// The tone's solid fill, and its ink on the quiet variants.
    pub accent_on_soft_press: Color,
    /// Ink that clears AA on the solid fill. Computed per theme — never `text.inverse`.
    pub accent_contrast: Color,
}

impl Palette {
    /// This palette's colours for one tone.
    ///
    /// Exhaustive over `Tone` with no wildcard arm, so adding a tone to the
    /// contract fails this file to compile rather than silently painting a default.
    #[must_use]
    pub const fn tone(&self, tone: Tone) -> ToneColors {
        match tone {
            Tone::Neutral => ToneColors {
                accent: self.text_primary,
                accent_hover: self.text_primary,
                accent_press: self.text_primary,
                accent_soft: self.bg_subtle,
                accent_soft_hover: self.state_hover_bg,
                accent_soft_press: self.state_press_bg,
                accent_on_soft: self.text_primary,
                accent_on_soft_hover: self.text_primary,
                accent_on_soft_press: self.text_primary,
                accent_contrast: self.text_inverse,
            },
            Tone::Brand => ToneColors {
                accent: self.brand_primary,
                accent_hover: self.brand_hover,
                accent_press: self.brand_press,
                accent_soft: self.brand_soft,
                accent_soft_hover: self.brand_soft_hover,
                accent_soft_press: self.brand_soft_press,
                accent_on_soft: self.brand_on_soft,
                accent_on_soft_hover: self.brand_on_soft_hover,
                accent_on_soft_press: self.brand_on_soft_press,
                accent_contrast: self.brand_contrast,
            },
            Tone::Accent => ToneColors {
                accent: self.accent_primary,
                accent_hover: self.accent_hover,
                accent_press: self.accent_press,
                accent_soft: self.accent_soft,
                accent_soft_hover: self.accent_soft_hover,
                accent_soft_press: self.accent_soft_press,
                accent_on_soft: self.accent_on_soft,
                accent_on_soft_hover: self.accent_on_soft_hover,
                accent_on_soft_press: self.accent_on_soft_press,
                accent_contrast: self.accent_contrast,
            },
            Tone::Success => ToneColors {
                accent: self.status_success,
                accent_hover: self.status_success_hover,
                accent_press: self.status_success_press,
                accent_soft: self.status_success_soft,
                accent_soft_hover: self.status_success_soft_hover,
                accent_soft_press: self.status_success_soft_hover,
                accent_on_soft: self.status_success_on_soft,
                accent_on_soft_hover: self.status_success_on_soft_hover,
                accent_on_soft_press: self.status_success_on_soft_hover,
                accent_contrast: self.status_success_contrast,
            },
            Tone::Warning => ToneColors {
                accent: self.status_warning,
                accent_hover: self.status_warning_hover,
                accent_press: self.status_warning_press,
                accent_soft: self.status_warning_soft,
                accent_soft_hover: self.status_warning_soft_hover,
                accent_soft_press: self.status_warning_soft_hover,
                accent_on_soft: self.status_warning_on_soft,
                accent_on_soft_hover: self.status_warning_on_soft_hover,
                accent_on_soft_press: self.status_warning_on_soft_hover,
                accent_contrast: self.status_warning_contrast,
            },
            Tone::Danger => ToneColors {
                accent: self.status_error,
                accent_hover: self.status_error_hover,
                accent_press: self.status_error_press,
                accent_soft: self.status_error_soft,
                accent_soft_hover: self.status_error_soft_hover,
                accent_soft_press: self.status_error_soft_hover,
                accent_on_soft: self.status_error_on_soft,
                accent_on_soft_hover: self.status_error_on_soft_hover,
                accent_on_soft_press: self.status_error_on_soft_hover,
                accent_contrast: self.status_error_contrast,
            },
            Tone::Info => ToneColors {
                accent: self.status_info,
                accent_hover: self.status_info_hover,
                accent_press: self.status_info_press,
                accent_soft: self.status_info_soft,
                accent_soft_hover: self.status_info_soft_hover,
                accent_soft_press: self.status_info_soft_hover,
                accent_on_soft: self.status_info_on_soft,
                accent_on_soft_hover: self.status_info_on_soft_hover,
                accent_on_soft_press: self.status_info_on_soft_hover,
                accent_contrast: self.status_info_contrast,
            },
        }
    }
}

/// One badge tone resolved against one palette, for one variant.
///
/// A fill and an edge may be absent — a ghost badge has neither. The ink never
/// is: a badge whose label cannot be read is not a badge.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct BadgeColors {
    /// Fill, or `None` for none.
    pub background: Option<Color>,
    /// Ink. Always present.
    pub text: Color,
    /// Edge, or `None` for none. Only `Outline` draws one.
    pub border: Option<Color>,
}

impl Palette {
    /// This palette's colours for one badge tone and variant.
    ///
    /// Exhaustive over both vocabularies with no wildcard arm, so adding a tone
    /// or a variant fails this file to compile rather than silently painting a
    /// default.
    #[must_use]
    pub const fn badge_tone(&self, tone: BadgeTone, variant: Variant) -> BadgeColors {
        match (tone, variant) {
            (BadgeTone::Neutral, Variant::Solid) => BadgeColors {
                background: Some(self.brand_primary),
                text: self.brand_contrast,
                border: None,
            },
            (BadgeTone::Neutral, Variant::Outline) => BadgeColors {
                background: Some(self.bg_surface),
                text: self.text_primary,
                border: Some(self.border_default),
            },
            (BadgeTone::Neutral, Variant::Ghost) => BadgeColors {
                background: None,
                text: self.text_muted,
                border: None,
            },
            (BadgeTone::Neutral, Variant::Soft) => BadgeColors {
                background: Some(self.brand_soft),
                text: self.brand_on_soft,
                border: None,
            },
            (BadgeTone::Success, Variant::Solid) => BadgeColors {
                background: Some(self.status_success),
                text: self.brand_contrast,
                border: None,
            },
            (BadgeTone::Success, Variant::Outline) => BadgeColors {
                background: Some(self.bg_surface),
                text: self.status_success,
                border: Some(self.status_success_border),
            },
            (BadgeTone::Success, Variant::Ghost) => BadgeColors {
                background: None,
                text: self.status_success,
                border: None,
            },
            (BadgeTone::Success, Variant::Soft) => BadgeColors {
                background: Some(self.status_success_soft),
                text: self.status_success_on_soft,
                border: None,
            },
            (BadgeTone::Warning, Variant::Solid) => BadgeColors {
                background: Some(self.status_warning),
                text: self.brand_contrast,
                border: None,
            },
            (BadgeTone::Warning, Variant::Outline) => BadgeColors {
                background: Some(self.bg_surface),
                text: self.status_warning,
                border: Some(self.status_warning_border),
            },
            (BadgeTone::Warning, Variant::Ghost) => BadgeColors {
                background: None,
                text: self.status_warning,
                border: None,
            },
            (BadgeTone::Warning, Variant::Soft) => BadgeColors {
                background: Some(self.status_warning_soft),
                text: self.status_warning_on_soft,
                border: None,
            },
            (BadgeTone::Danger, Variant::Solid) => BadgeColors {
                background: Some(self.status_error),
                text: self.brand_contrast,
                border: None,
            },
            (BadgeTone::Danger, Variant::Outline) => BadgeColors {
                background: Some(self.bg_surface),
                text: self.status_error,
                border: Some(self.status_error_border),
            },
            (BadgeTone::Danger, Variant::Ghost) => BadgeColors {
                background: None,
                text: self.status_error,
                border: None,
            },
            (BadgeTone::Danger, Variant::Soft) => BadgeColors {
                background: Some(self.status_error_soft),
                text: self.status_error_on_soft,
                border: None,
            },
            (BadgeTone::Info, Variant::Solid) => BadgeColors {
                background: Some(self.status_info),
                text: self.brand_contrast,
                border: None,
            },
            (BadgeTone::Info, Variant::Outline) => BadgeColors {
                background: Some(self.bg_surface),
                text: self.status_info,
                border: Some(self.status_info_border),
            },
            (BadgeTone::Info, Variant::Ghost) => BadgeColors {
                background: None,
                text: self.status_info,
                border: None,
            },
            (BadgeTone::Info, Variant::Soft) => BadgeColors {
                background: Some(self.status_info_soft),
                text: self.status_info_on_soft,
                border: None,
            },
        }
    }
}

/// The light theme TreeUI ships.
pub const LIGHT: Palette = Palette {
    mode: ColorMode::Light,
    bg_primary: Color { r: 246, g: 248, b: 250, a: 1.0 },
    bg_surface: Color { r: 255, g: 255, b: 255, a: 1.0 },
    bg_subtle: Color { r: 239, g: 242, b: 245, a: 1.0 },
    border_default: Color { r: 208, g: 215, b: 222, a: 1.0 },
    border_strong: Color { r: 175, g: 184, b: 193, a: 1.0 },
    text_primary: Color { r: 31, g: 35, b: 40, a: 1.0 },
    text_muted: Color { r: 89, g: 99, b: 110, a: 1.0 },
    text_inverse: Color { r: 255, g: 255, b: 255, a: 1.0 },
    shadow_rgb: Color { r: 15, g: 23, b: 42, a: 1.0 },
    brand_primary: Color { r: 9, g: 105, b: 218, a: 1.0 },
    brand_hover: Color { r: 5, g: 80, b: 174, a: 1.0 },
    brand_soft: Color { r: 221, g: 244, b: 255, a: 1.0 },
    brand_contrast: Color { r: 255, g: 255, b: 255, a: 1.0 },
    accent_primary: Color { r: 121, g: 77, b: 203, a: 1.0 },
    accent_hover: Color { r: 99, g: 63, b: 166, a: 1.0 },
    accent_soft: Color { r: 239, g: 234, b: 249, a: 1.0 },
    accent_contrast: Color { r: 255, g: 255, b: 255, a: 1.0 },
    status_success: Color { r: 25, g: 125, b: 54, a: 1.0 },
    status_warning: Color { r: 148, g: 99, b: 0, a: 1.0 },
    status_error: Color { r: 209, g: 36, b: 47, a: 1.0 },
    status_info: Color { r: 9, g: 105, b: 218, a: 1.0 },
    chart_1: Color { r: 42, g: 120, b: 214, a: 1.0 },
    chart_2: Color { r: 18, g: 133, b: 92, a: 1.0 },
    chart_3: Color { r: 138, g: 97, b: 0, a: 1.0 },
    chart_4: Color { r: 0, g: 131, b: 0, a: 1.0 },
    chart_5: Color { r: 74, g: 58, b: 167, a: 1.0 },
    chart_6: Color { r: 227, g: 73, b: 72, a: 1.0 },
    chart_7: Color { r: 196, g: 88, b: 127, a: 1.0 },
    chart_8: Color { r: 235, g: 104, b: 52, a: 1.0 },
    overlay: Color { r: 31, g: 35, b: 40, a: 0.5 },
    focus_ring: Color { r: 9, g: 105, b: 218, a: 0.32 },
    border_interactive: Color { r: 129, g: 135, b: 142, a: 1.0 },
    brand_press: Color { r: 6, g: 71, b: 148, a: 1.0 },
    brand_soft_hover: Color { r: 191, g: 225, b: 250, a: 1.0 },
    brand_soft_press: Color { r: 166, g: 208, b: 245, a: 1.0 },
    brand_on_soft: Color { r: 9, g: 105, b: 218, a: 1.0 },
    brand_on_soft_hover: Color { r: 8, g: 90, b: 187, a: 1.0 },
    brand_on_soft_press: Color { r: 7, g: 81, b: 169, a: 1.0 },
    accent_press: Color { r: 82, g: 52, b: 138, a: 1.0 },
    accent_soft_hover: Color { r: 222, g: 212, b: 243, a: 1.0 },
    accent_soft_press: Color { r: 208, g: 193, b: 237, a: 1.0 },
    accent_on_soft: Color { r: 121, g: 77, b: 203, a: 1.0 },
    accent_on_soft_hover: Color { r: 109, g: 69, b: 183, a: 1.0 },
    accent_on_soft_press: Color { r: 99, g: 63, b: 165, a: 1.0 },
    status_success_hover: Color { r: 21, g: 103, b: 44, a: 1.0 },
    status_success_press: Color { r: 17, g: 85, b: 37, a: 1.0 },
    status_success_soft: Color { r: 223, g: 237, b: 227, a: 1.0 },
    status_success_soft_hover: Color { r: 195, g: 221, b: 203, a: 1.0 },
    status_success_border: Color { r: 65, g: 147, b: 89, a: 1.0 },
    status_success_contrast: Color { r: 255, g: 255, b: 255, a: 1.0 },
    status_success_on_soft: Color { r: 24, g: 119, b: 51, a: 1.0 },
    status_success_on_soft_hover: Color { r: 21, g: 107, b: 46, a: 1.0 },
    status_warning_hover: Color { r: 121, g: 81, b: 0, a: 1.0 },
    status_warning_press: Color { r: 101, g: 67, b: 0, a: 1.0 },
    status_warning_soft: Color { r: 240, g: 233, b: 219, a: 1.0 },
    status_warning_soft_hover: Color { r: 227, g: 214, b: 188, a: 1.0 },
    status_warning_border: Color { r: 166, g: 126, b: 44, a: 1.0 },
    status_warning_contrast: Color { r: 255, g: 255, b: 255, a: 1.0 },
    status_warning_on_soft: Color { r: 141, g: 94, b: 0, a: 1.0 },
    status_warning_on_soft_hover: Color { r: 127, g: 85, b: 0, a: 1.0 },
    status_error_hover: Color { r: 171, g: 30, b: 39, a: 1.0 },
    status_error_press: Color { r: 142, g: 24, b: 32, a: 1.0 },
    status_error_soft: Color { r: 249, g: 224, b: 226, a: 1.0 },
    status_error_soft_hover: Color { r: 243, g: 198, b: 201, a: 1.0 },
    status_error_border: Color { r: 219, g: 83, b: 92, a: 1.0 },
    status_error_contrast: Color { r: 255, g: 255, b: 255, a: 1.0 },
    status_error_on_soft: Color { r: 199, g: 34, b: 45, a: 1.0 },
    status_error_on_soft_hover: Color { r: 170, g: 29, b: 38, a: 1.0 },
    status_info_hover: Color { r: 7, g: 86, b: 179, a: 1.0 },
    status_info_press: Color { r: 6, g: 71, b: 148, a: 1.0 },
    status_info_soft: Color { r: 221, g: 234, b: 250, a: 1.0 },
    status_info_soft_hover: Color { r: 191, g: 216, b: 246, a: 1.0 },
    status_info_border: Color { r: 51, g: 131, b: 224, a: 1.0 },
    status_info_contrast: Color { r: 255, g: 255, b: 255, a: 1.0 },
    status_info_on_soft: Color { r: 9, g: 100, b: 207, a: 1.0 },
    status_info_on_soft_hover: Color { r: 8, g: 90, b: 187, a: 1.0 },
    state_hover_bg: Color { r: 242, g: 242, b: 242, a: 1.0 },
    state_press_bg: Color { r: 228, g: 229, b: 229, a: 1.0 },
    state_selected_bg: Color { r: 221, g: 244, b: 255, a: 1.0 },
    state_selected_fg: Color { r: 9, g: 105, b: 218, a: 1.0 },
    state_selected_border: Color { r: 9, g: 105, b: 218, a: 1.0 },
    state_disabled_bg: Color { r: 239, g: 242, b: 245, a: 1.0 },
    state_disabled_fg: Color { r: 127, g: 135, b: 144, a: 1.0 },
    state_disabled_border: Color { r: 222, g: 227, b: 232, a: 1.0 },
    shadow_xs: &[ShadowLayer { offset_x: 0.0, offset_y: 1.0, blur: 2.0, spread: 0.0, color: Color { r: 15, g: 23, b: 42, a: 0.06 } }],
    shadow_sm: &[ShadowLayer { offset_x: 0.0, offset_y: 6.0, blur: 18.0, spread: 0.0, color: Color { r: 15, g: 23, b: 42, a: 0.08 } }],
    shadow_md: &[ShadowLayer { offset_x: 0.0, offset_y: 14.0, blur: 34.0, spread: 0.0, color: Color { r: 15, g: 23, b: 42, a: 0.12 } }],
    shadow_lg: &[ShadowLayer { offset_x: 0.0, offset_y: 24.0, blur: 48.0, spread: -24.0, color: Color { r: 15, g: 23, b: 42, a: 0.22 } }],
    shadow_xl: &[ShadowLayer { offset_x: 0.0, offset_y: 40.0, blur: 80.0, spread: -32.0, color: Color { r: 15, g: 23, b: 42, a: 0.28 } }],
    shadow_accent: &[ShadowLayer { offset_x: 0.0, offset_y: 24.0, blur: 48.0, spread: -32.0, color: Color { r: 121, g: 77, b: 203, a: 0.6 } }],
    gradient_brand: Gradient { angle_deg: 135.0, stops: &[GradientStop { color: Color { r: 9, g: 105, b: 218, a: 1.0 }, position_pct: None }, GradientStop { color: Color { r: 5, g: 80, b: 174, a: 1.0 }, position_pct: None }] },
};

/// The dark theme TreeUI ships.
pub const DARK: Palette = Palette {
    mode: ColorMode::Dark,
    bg_primary: Color { r: 28, g: 33, b: 40, a: 1.0 },
    bg_surface: Color { r: 34, g: 39, b: 46, a: 1.0 },
    bg_subtle: Color { r: 45, g: 51, b: 59, a: 1.0 },
    border_default: Color { r: 68, g: 76, b: 86, a: 1.0 },
    border_strong: Color { r: 87, g: 98, b: 112, a: 1.0 },
    text_primary: Color { r: 173, g: 186, b: 199, a: 1.0 },
    text_muted: Color { r: 149, g: 163, b: 178, a: 1.0 },
    text_inverse: Color { r: 28, g: 33, b: 40, a: 1.0 },
    shadow_rgb: Color { r: 0, g: 0, b: 0, a: 1.0 },
    brand_primary: Color { r: 85, g: 156, b: 245, a: 1.0 },
    brand_hover: Color { r: 108, g: 171, b: 247, a: 1.0 },
    brand_soft: Color { r: 26, g: 52, b: 83, a: 1.0 },
    brand_contrast: Color { r: 10, g: 26, b: 47, a: 1.0 },
    accent_primary: Color { r: 173, g: 139, b: 237, a: 1.0 },
    accent_hover: Color { r: 186, g: 157, b: 240, a: 1.0 },
    accent_soft: Color { r: 51, g: 46, b: 74, a: 1.0 },
    accent_contrast: Color { r: 28, g: 33, b: 40, a: 1.0 },
    status_success: Color { r: 91, g: 174, b: 94, a: 1.0 },
    status_warning: Color { r: 201, g: 146, b: 39, a: 1.0 },
    status_error: Color { r: 245, g: 118, b: 110, a: 1.0 },
    status_info: Color { r: 108, g: 182, b: 255, a: 1.0 },
    chart_1: Color { r: 57, g: 135, b: 229, a: 1.0 },
    chart_2: Color { r: 25, g: 158, b: 112, a: 1.0 },
    chart_3: Color { r: 201, g: 133, b: 0, a: 1.0 },
    chart_4: Color { r: 0, g: 131, b: 0, a: 1.0 },
    chart_5: Color { r: 144, g: 133, b: 233, a: 1.0 },
    chart_6: Color { r: 230, g: 103, b: 103, a: 1.0 },
    chart_7: Color { r: 213, g: 81, b: 129, a: 1.0 },
    chart_8: Color { r: 217, g: 89, b: 38, a: 1.0 },
    overlay: Color { r: 13, g: 17, b: 23, a: 0.6 },
    focus_ring: Color { r: 85, g: 156, b: 245, a: 0.32 },
    border_interactive: Color { r: 118, g: 127, b: 139, a: 1.0 },
    brand_press: Color { r: 139, g: 188, b: 248, a: 1.0 },
    brand_soft_hover: Color { r: 34, g: 67, b: 106, a: 1.0 },
    brand_soft_press: Color { r: 41, g: 79, b: 125, a: 1.0 },
    brand_on_soft: Color { r: 94, g: 161, b: 246, a: 1.0 },
    brand_on_soft_hover: Color { r: 123, g: 178, b: 247, a: 1.0 },
    brand_on_soft_press: Color { r: 153, g: 196, b: 249, a: 1.0 },
    accent_press: Color { r: 199, g: 176, b: 243, a: 1.0 },
    accent_soft_hover: Color { r: 68, g: 59, b: 97, a: 1.0 },
    accent_soft_press: Color { r: 83, g: 70, b: 116, a: 1.0 },
    accent_on_soft: Color { r: 173, g: 139, b: 237, a: 1.0 },
    accent_on_soft_hover: Color { r: 188, g: 161, b: 240, a: 1.0 },
    accent_on_soft_press: Color { r: 203, g: 182, b: 244, a: 1.0 },
    status_success_hover: Color { r: 121, g: 189, b: 123, a: 1.0 },
    status_success_press: Color { r: 143, g: 200, b: 146, a: 1.0 },
    status_success_soft: Color { r: 42, g: 58, b: 53, a: 1.0 },
    status_success_soft_hover: Color { r: 49, g: 74, b: 59, a: 1.0 },
    status_success_border: Color { r: 79, g: 145, b: 84, a: 1.0 },
    status_success_contrast: Color { r: 28, g: 33, b: 40, a: 1.0 },
    status_success_on_soft: Color { r: 99, g: 178, b: 102, a: 1.0 },
    status_success_on_soft_hover: Color { r: 128, g: 192, b: 130, a: 1.0 },
    status_warning_hover: Color { r: 211, g: 166, b: 78, a: 1.0 },
    status_warning_press: Color { r: 218, g: 181, b: 108, a: 1.0 },
    status_warning_soft: Color { r: 57, g: 54, b: 45, a: 1.0 },
    status_warning_soft_hover: Color { r: 77, g: 67, b: 44, a: 1.0 },
    status_warning_border: Color { r: 165, g: 123, b: 41, a: 1.0 },
    status_warning_contrast: Color { r: 28, g: 33, b: 40, a: 1.0 },
    status_warning_on_soft: Color { r: 204, g: 151, b: 50, a: 1.0 },
    status_warning_on_soft_hover: Color { r: 213, g: 171, b: 88, a: 1.0 },
    status_error_hover: Color { r: 247, g: 143, b: 136, a: 1.0 },
    status_error_press: Color { r: 248, g: 162, b: 156, a: 1.0 },
    status_error_soft: Color { r: 64, g: 50, b: 55, a: 1.0 },
    status_error_soft_hover: Color { r: 89, g: 60, b: 63, a: 1.0 },
    status_error_border: Color { r: 200, g: 101, b: 96, a: 1.0 },
    status_error_contrast: Color { r: 28, g: 33, b: 40, a: 1.0 },
    status_error_on_soft: Color { r: 246, g: 125, b: 117, a: 1.0 },
    status_error_on_soft_hover: Color { r: 247, g: 149, b: 143, a: 1.0 },
    status_info_hover: Color { r: 134, g: 195, b: 255, a: 1.0 },
    status_info_press: Color { r: 155, g: 205, b: 255, a: 1.0 },
    status_info_soft: Color { r: 44, g: 59, b: 75, a: 1.0 },
    status_info_soft_hover: Color { r: 53, g: 76, b: 100, a: 1.0 },
    status_info_border: Color { r: 86, g: 139, b: 192, a: 1.0 },
    status_info_contrast: Color { r: 28, g: 33, b: 40, a: 1.0 },
    status_info_on_soft: Color { r: 108, g: 182, b: 255, a: 1.0 },
    status_info_on_soft_hover: Color { r: 129, g: 192, b: 255, a: 1.0 },
    state_hover_bg: Color { r: 42, g: 48, b: 55, a: 1.0 },
    state_press_bg: Color { r: 51, g: 57, b: 64, a: 1.0 },
    state_selected_bg: Color { r: 26, g: 52, b: 83, a: 1.0 },
    state_selected_fg: Color { r: 94, g: 161, b: 246, a: 1.0 },
    state_selected_border: Color { r: 85, g: 156, b: 245, a: 1.0 },
    state_disabled_bg: Color { r: 45, g: 51, b: 59, a: 1.0 },
    state_disabled_fg: Color { r: 118, g: 129, b: 142, a: 1.0 },
    state_disabled_border: Color { r: 58, g: 65, b: 74, a: 1.0 },
    shadow_xs: &[ShadowLayer { offset_x: 0.0, offset_y: 1.0, blur: 2.0, spread: 0.0, color: Color { r: 0, g: 0, b: 0, a: 0.06 } }],
    shadow_sm: &[ShadowLayer { offset_x: 0.0, offset_y: 6.0, blur: 18.0, spread: 0.0, color: Color { r: 0, g: 0, b: 0, a: 0.08 } }],
    shadow_md: &[ShadowLayer { offset_x: 0.0, offset_y: 14.0, blur: 34.0, spread: 0.0, color: Color { r: 0, g: 0, b: 0, a: 0.12 } }],
    shadow_lg: &[ShadowLayer { offset_x: 0.0, offset_y: 24.0, blur: 48.0, spread: -24.0, color: Color { r: 0, g: 0, b: 0, a: 0.22 } }],
    shadow_xl: &[ShadowLayer { offset_x: 0.0, offset_y: 40.0, blur: 80.0, spread: -32.0, color: Color { r: 0, g: 0, b: 0, a: 0.28 } }],
    shadow_accent: &[ShadowLayer { offset_x: 0.0, offset_y: 24.0, blur: 48.0, spread: -32.0, color: Color { r: 173, g: 139, b: 237, a: 0.6 } }],
    gradient_brand: Gradient { angle_deg: 135.0, stops: &[GradientStop { color: Color { r: 85, g: 156, b: 245, a: 1.0 }, position_pct: None }, GradientStop { color: Color { r: 108, g: 171, b: 247, a: 1.0 }, position_pct: None }] },
};
