// Generated by @treeui/tokens. DO NOT EDIT.
// Regenerate with: pnpm codegen:native
// Colour contract version: 1.0

package treeui.tokens

/**
 * The TreeUI token layer, resolved for Kotlin.
 *
 * Lengths are density-independent pixels and type sizes are scalable pixels,
 * both taken from the CSS model at its authored root size of
 * 16px — one CSS pixel is one `dp`. Nothing here imports Compose, so
 * this module also serves a plain-JVM or a Compose Multiplatform consumer.
 */
public object TreeTokens {
    /** The colour contract this file was generated against. */
    public const val CONTRACT_VERSION: String = "1.0"

    /** The CSS root font size the lengths below were resolved against. */
    public const val ROOT_FONT_SIZE_PX: Float = 16.0f

    /** Font stacks, most preferred family first. */
    public object FontFamily {
        /** `--tree-font-family-sans` */
        public val sans: List<String> = listOf("Google Sans Flex", "Segoe UI", "sans-serif")
        /** `--tree-font-family-mono` */
        public val mono: List<String> = listOf("Google Sans Code", "SFMono-Regular", "monospace")
    }

    /** Type scale. These follow the reader’s text-size setting — scalable pixels, not device-independent ones. */
    public object FontSize {
        /** `--tree-font-size-xs` */
        public val xs: Float = 11.0f
        /** `--tree-font-size-sm` */
        public val sm: Float = 13.0f
        /** `--tree-font-size-md` */
        public val md: Float = 15.0f
        /** `--tree-font-size-base` */
        public val base: Float = 15.0f
        /** `--tree-font-size-lg` */
        public val lg: Float = 18.0f
        /** `--tree-font-size-xl` */
        public val xl: Float = 22.0f
        /** `--tree-font-size-2xl` */
        public val xl2: Float = 24.0f
        /** `--tree-font-size-3xl` */
        public val xl3: Float = 28.0f
        /** `--tree-font-size-4xl` */
        public val xl4: Float = 36.0f
        /** `--tree-font-size-5xl` */
        public val xl5: Float = 48.0f
    }

    /** CSS numeric weights, which every target maps 1:1. */
    public object FontWeight {
        /** `--tree-font-weight-regular` */
        public val regular: Int = 400
        /** `--tree-font-weight-medium` */
        public val medium: Int = 500
        /** `--tree-font-weight-semibold` */
        public val semibold: Int = 600
        /** `--tree-font-weight-bold` */
        public val bold: Int = 700
        /** `--tree-font-weight-extrabold` */
        public val extrabold: Int = 800
    }

    /** Unitless multipliers of the font size. */
    public object LineHeight {
        /** `--tree-font-lineHeight-compact` */
        public val compact: Float = 1.1f
        /** `--tree-font-lineHeight-ui` */
        public val ui: Float = 1.15f
        /** `--tree-font-lineHeight-tight` */
        public val tight: Float = 1.25f
        /** `--tree-font-lineHeight-heading` */
        public val heading: Float = 1.3f
        /** `--tree-font-lineHeight-base` */
        public val base: Float = 1.5f
        /** `--tree-font-lineHeight-body` */
        public val body: Float = 1.6f
        /** `--tree-font-lineHeight-relaxed` */
        public val relaxed: Float = 1.65f
    }

    /** Letter spacing as a multiple of the font size (CSS `em`). */
    public object Tracking {
        /** `--tree-font-tracking-tight` */
        public val tight: Float = -0.02f
        /** `--tree-font-tracking-normal` */
        public val normal: Float = 0.0f
        /** `--tree-font-tracking-wide` */
        public val wide: Float = 0.08f
    }

    /** Spacing scale, in pixels. */
    public object Space {
        /** `--tree-space-0` */
        public val s0: Float = 0.0f
        /** `--tree-space-1` */
        public val s1: Float = 4.0f
        /** `--tree-space-2` */
        public val s2: Float = 8.0f
        /** `--tree-space-3` */
        public val s3: Float = 12.0f
        /** `--tree-space-4` */
        public val s4: Float = 16.0f
        /** `--tree-space-5` */
        public val s5: Float = 20.0f
        /** `--tree-space-6` */
        public val s6: Float = 24.0f
        /** `--tree-space-8` */
        public val s8: Float = 32.0f
        /** `--tree-space-12` */
        public val s12: Float = 48.0f
        /** `--tree-space-16` */
        public val s16: Float = 64.0f
    }

    /** Corner radii, in pixels. */
    public object Radius {
        /** `--tree-radius-sm` */
        public val sm: Float = 6.0f
        /** `--tree-radius-md` */
        public val md: Float = 10.0f
        /** `--tree-radius-lg` */
        public val lg: Float = 14.0f
        /** `--tree-radius-pill` */
        public val pill: Float = 999.0f
    }

    /** Control heights, in pixels — one per size step. */
    public object ControlSize {
        /** `--tree-size-control-sm` */
        public val sm: Float = 32.0f
        /** `--tree-size-control-md` */
        public val md: Float = 40.0f
        /** `--tree-size-control-lg` */
        public val lg: Float = 48.0f
    }

    /** Icon box sizes, in pixels. */
    public object IconSize {
        /** `--tree-size-icon-sm` */
        public val sm: Float = 16.0f
        /** `--tree-size-icon-md` */
        public val md: Float = 20.0f
        /** `--tree-size-icon-lg` */
        public val lg: Float = 24.0f
        /** `--tree-size-icon-xl` */
        public val xl: Float = 32.0f
        /** `--tree-size-icon-2xl` */
        public val xl2: Float = 48.0f
    }

    /** Stroke widths, in pixels. */
    public object BorderWidth {
        /** `--tree-border-width-subtle` */
        public val subtle: Float = 1.0f
        /** `--tree-border-width-strong` */
        public val strong: Float = 1.5f
    }

    /** Grid gutters, in pixels. */
    public object Gutter {
        /** `--tree-layout-gutter-sm` */
        public val sm: Float = 16.0f
        /** `--tree-layout-gutter-md` */
        public val md: Float = 24.0f
    }

    /** Page margins, in pixels. */
    public object Margin {
        /** `--tree-layout-margin-sm` */
        public val sm: Float = 24.0f
        /** `--tree-layout-margin-md` */
        public val md: Float = 32.0f
        /** `--tree-layout-margin-lg` */
        public val lg: Float = 48.0f
    }

    /** The layout grid itself: its column count and its base unit. */
    public object Grid {
        /** `--tree-layout-grid-base` */
        public val base: Float = 8.0f
        /** `--tree-layout-grid-columns` */
        public val columns: Int = 12
    }

    /** Viewport widths, in pixels. */
    public object Breakpoint {
        /** `--tree-breakpoint-sm` */
        public val sm: Float = 640.0f
        /** `--tree-breakpoint-md` */
        public val md: Float = 768.0f
        /** `--tree-breakpoint-lg` */
        public val lg: Float = 1024.0f
        /** `--tree-breakpoint-xl` */
        public val xl: Float = 1280.0f
    }

    /** The one opacity the system uses, for the parts of a disabled control that carry no text. */
    public object Opacity {
        /** `--tree-opacity-disabled` */
        public val disabled: Float = 0.5f
    }

    /** Animation durations, in milliseconds. */
    public object Duration {
        /** `--tree-motion-duration-fast` */
        public val fast: Int = 100
        /** `--tree-motion-duration-moderate` */
        public val moderate: Int = 200
        /** `--tree-motion-duration-normal` */
        public val normal: Int = 300
        /** `--tree-motion-duration-slow` */
        public val slow: Int = 400
        /** `--tree-motion-duration-slower` */
        public val slower: Int = 500
    }

    /** Cubic-bezier timing functions, as their four control values. */
    public object Easing {
        /** `--tree-motion-easing-standard` */
        public val standard: TreeEasing = TreeEasing(0.2f, 0.0f, 0.0f, 1.0f)
        /** `--tree-motion-easing-easeOut` */
        public val easeOut: TreeEasing = TreeEasing(0.0f, 0.0f, 0.2f, 1.0f)
        /** `--tree-motion-easing-easeInOut` */
        public val easeInOut: TreeEasing = TreeEasing(0.4f, 0.0f, 0.2f, 1.0f)
        /** `--tree-motion-easing-easeIn` */
        public val easeIn: TreeEasing = TreeEasing(0.4f, 0.0f, 1.0f, 1.0f)
    }

    /** Stacking order. A retained-mode target draws in declaration order, so these are the tie-break for overlay surfaces. */
    public object ZIndex {
        /** `--tree-z-base` */
        public val base: Int = 1
        /** `--tree-z-dropdown` */
        public val dropdown: Int = 1000
        /** `--tree-z-popover` */
        public val popover: Int = 1050
        /** `--tree-z-sticky` */
        public val sticky: Int = 1100
        /** `--tree-z-overlay` */
        public val overlay: Int = 1200
        /** `--tree-z-modal` */
        public val modal: Int = 1300
        /** `--tree-z-toast` */
        public val toast: Int = 1400
    }
}

/**
 * Size steps, shared by most components.
 */
public enum class TreeSize {
    /** `"sm"` */
    Sm,
    /** `"md"` */
    Md,
    /** `"lg"` */
    Lg,
    ;

    /** The string this member is spelled with on the web — its CSS modifier and its JS prop value. */
    public val token: String
        get() =
            when (this) {
                Sm -> "sm"
                Md -> "md"
                Lg -> "lg"
            }
}

/**
 * Shape scale for an action surface. Orthogonal to its tone.
 *
 * `danger` is absent on purpose: it is a colour trapped in the shape scale, so it could only ever be a filled red button. Use `Solid` with `Tone::Danger`, which composes with the quiet variants too.
 */
public enum class TreeVariant {
    /** `"solid"` */
    Solid,
    /** `"outline"` */
    Outline,
    /** `"ghost"` */
    Ghost,
    /** `"soft"` */
    Soft,
    ;

    /** The string this member is spelled with on the web — its CSS modifier and its JS prop value. */
    public val token: String
        get() =
            when (this) {
                Solid -> "solid"
                Outline -> "outline"
                Ghost -> "ghost"
                Soft -> "soft"
            }
}

/**
 * Surface scale for a card — not action variants. `solid` is deliberately absent.
 */
public enum class TreeCardVariant {
    /** `"outline"` */
    Outline,
    /** `"soft"` */
    Soft,
    /** `"inset"` */
    Inset,
    ;

    /** The string this member is spelled with on the web — its CSS modifier and its JS prop value. */
    public val token: String
        get() =
            when (this) {
                Outline -> "outline"
                Soft -> "soft"
                Inset -> "inset"
            }
}

/**
 * Tone set for a component that states a status rather than offering an action. Narrower than `Tone`: no brand, no accent.
 */
public enum class TreeBadgeTone {
    /** `"neutral"` */
    Neutral,
    /** `"success"` */
    Success,
    /** `"warning"` */
    Warning,
    /** `"danger"` */
    Danger,
    /** `"info"` */
    Info,
    ;

    /** The string this member is spelled with on the web — its CSS modifier and its JS prop value. */
    public val token: String
        get() =
            when (this) {
                Neutral -> "neutral"
                Success -> "success"
                Warning -> "warning"
                Danger -> "danger"
                Info -> "info"
            }
}

/**
 * The accent axis a surface declares and its descendants inherit.
 */
public enum class TreeAccent {
    /** `"brand"` */
    Brand,
    /** `"neutral"` */
    Neutral,
    /** `"success"` */
    Success,
    /** `"warning"` */
    Warning,
    /** `"danger"` */
    Danger,
    /** `"info"` */
    Info,
    ;

    /** The string this member is spelled with on the web — its CSS modifier and its JS prop value. */
    public val token: String
        get() =
            when (this) {
                Brand -> "brand"
                Neutral -> "neutral"
                Success -> "success"
                Warning -> "warning"
                Danger -> "danger"
                Info -> "info"
            }
}

/**
 * Inline-size scale for a form control. Controls fill their container by default.
 */
public enum class TreeFieldWidth {
    /** `"xs"` */
    Xs,
    /** `"sm"` */
    Sm,
    /** `"md"` */
    Md,
    /** `"lg"` */
    Lg,
    /** `"xl"` */
    Xl,
    /** `"full"` */
    Full,
    ;

    /** The string this member is spelled with on the web — its CSS modifier and its JS prop value. */
    public val token: String
        get() =
            when (this) {
                Xs -> "xs"
                Sm -> "sm"
                Md -> "md"
                Lg -> "lg"
                Xl -> "xl"
                Full -> "full"
            }
}

/**
 * Placement for a tooltip, relative to its trigger.
 */
public enum class TreeTooltipSide {
    /** `"top"` */
    Top,
    /** `"right"` */
    Right,
    /** `"bottom"` */
    Bottom,
    /** `"left"` */
    Left,
    ;

    /** The string this member is spelled with on the web — its CSS modifier and its JS prop value. */
    public val token: String
        get() =
            when (this) {
                Top -> "top"
                Right -> "right"
                Bottom -> "bottom"
                Left -> "left"
            }
}

/**
 * Edge a drawer enters from.
 */
public enum class TreeDrawerSide {
    /** `"top"` */
    Top,
    /** `"right"` */
    Right,
    /** `"bottom"` */
    Bottom,
    /** `"left"` */
    Left,
    ;

    /** The string this member is spelled with on the web — its CSS modifier and its JS prop value. */
    public val token: String
        get() =
            when (this) {
                Top -> "top"
                Right -> "right"
                Bottom -> "bottom"
                Left -> "left"
            }
}

/**
 * Breakpoint names, paired with the `breakpoint-*` lengths.
 */
public enum class TreeBreakpoint {
    /** `"sm"` */
    Sm,
    /** `"md"` */
    Md,
    /** `"lg"` */
    Lg,
    /** `"xl"` */
    Xl,
    ;

    /** The string this member is spelled with on the web — its CSS modifier and its JS prop value. */
    public val token: String
        get() =
            when (this) {
                Sm -> "sm"
                Md -> "md"
                Lg -> "lg"
                Xl -> "xl"
            }
}

/**
 * One theme, fully resolved: the semantic colours a product fills in, the
 * interaction states the library derives from them, and the two groups whose
 * CSS refers to theme variables and so can only exist per theme.
 *
 * Every property is required. A theme assembled by hand that omits one does
 * not compile, which is the Kotlin form of the contract validator.
 */
public data class TreePalette(
    /** Which of the two colour modes this palette is, for the platform status bar and for `states.ts` parity. */
    public val mode: TreeColorMode,
    /** `--tree-color-bg-primary` — The page canvas, behind everything else. */
    public val bgPrimary: TreeColor,
    /** `--tree-color-bg-surface` — A raised surface sitting on the canvas: card, modal, popover, table head. */
    public val bgSurface: TreeColor,
    /** `--tree-color-bg-subtle` — A recessed or quiet band inside a surface: inset card, code block, disabled field. */
    public val bgSubtle: TreeColor,
    /** `--tree-color-border-default` — Decorative edges — card outline, divider, table rule. Not a control boundary. */
    public val borderDefault: TreeColor,
    /** `--tree-color-border-strong` — An emphasised decorative edge, and the hover edge of a quiet control. */
    public val borderStrong: TreeColor,
    /** `--tree-color-text-primary` — Body and heading ink on any bg.* surface. */
    public val textPrimary: TreeColor,
    /** `--tree-color-text-muted` — Secondary ink: help text, captions, placeholders. Still passes AA. */
    public val textMuted: TreeColor,
    /** `--tree-color-text-inverse` — Ink for a surface that inverts the theme. NOT the ink for a brand fill — that is brand.contrast, which is computed per theme. */
    public val textInverse: TreeColor,
    /** `--tree-color-shadow-rgb` — Umbra as an "r, g, b" triple. The elevation scale varies alpha over it. */
    public val shadowRgb: TreeColor,
    /** `--tree-color-brand-primary` — The product accent: primary action fill, active nav, focus emphasis, links. */
    public val brandPrimary: TreeColor,
    /** `--tree-color-brand-hover` — Hover fill for a solid brand surface. Public for compatibility; new state tokens are derived. Seeding a theme computes this for you. */
    public val brandHover: TreeColor,
    /** `--tree-color-brand-soft` — Brand tint: soft button, selected row, badge background. Carries brand ink. */
    public val brandSoft: TreeColor,
    /** `--tree-color-brand-contrast` — Ink ON a solid brand fill. Computed per theme by whichever of black/white reads better on that accent — never hardcoded in a component. */
    public val brandContrast: TreeColor,
    /** `--tree-color-accent-primary` — Secondary accent, for surfaces that need a second voice next to brand. */
    public val accentPrimary: TreeColor,
    /** `--tree-color-accent-hover` — Hover fill for a solid secondary-accent surface. */
    public val accentHover: TreeColor,
    /** `--tree-color-accent-soft` — Secondary-accent tint. Carries accent ink. */
    public val accentSoft: TreeColor,
    /** `--tree-color-accent-contrast` — Ink ON a solid secondary-accent fill. Computed per theme. */
    public val accentContrast: TreeColor,
    /** `--tree-color-status-success` — Confirmed / healthy. Independent of brand — do not remap it to the accent. */
    public val statusSuccess: TreeColor,
    /** `--tree-color-status-warning` — Needs attention, not yet broken. */
    public val statusWarning: TreeColor,
    /** `--tree-color-status-error` — Failed / destructive. Also the ink for validation messages. */
    public val statusError: TreeColor,
    /** `--tree-color-status-info` — Neutral information. Ships equal to brand.primary in the default theme; a product with a non-blue accent should set this so info stays distinguishable. */
    public val statusInfo: TreeColor,
    /** `--tree-color-chart-1` — Categorical series 1. Fixed hue order; assign in sequence. */
    public val chart1: TreeColor,
    /** `--tree-color-chart-2` — Categorical series 2. Fixed hue order; assign in sequence. */
    public val chart2: TreeColor,
    /** `--tree-color-chart-3` — Categorical series 3. Fixed hue order; assign in sequence. */
    public val chart3: TreeColor,
    /** `--tree-color-chart-4` — Categorical series 4. Fixed hue order; assign in sequence. */
    public val chart4: TreeColor,
    /** `--tree-color-chart-5` — Categorical series 5. Fixed hue order; assign in sequence. */
    public val chart5: TreeColor,
    /** `--tree-color-chart-6` — Categorical series 6. Fixed hue order; assign in sequence. */
    public val chart6: TreeColor,
    /** `--tree-color-chart-7` — Categorical series 7. Fixed hue order; assign in sequence. */
    public val chart7: TreeColor,
    /** `--tree-color-chart-8` — Categorical series 8. Fixed hue order; assign in sequence. */
    public val chart8: TreeColor,
    /** `--tree-color-overlay` — Scrim behind a modal or drawer. Carries alpha. */
    public val overlay: TreeColor,
    /** `--tree-color-focus-ring` — The focus indicator. Carries alpha; width is --tree-focus-ring-width. */
    public val focusRing: TreeColor,
    /** `--tree-color-border-interactive` — The boundary that identifies a form control (input, select, checkbox, radio). Must clear 3:1 on every surface — WCAG 1.4.11. Derived when omitted. */
    public val borderInteractive: TreeColor,
    /** `--tree-color-brand-press` — derived by the library from the semantic layer. Read it; never set it. */
    public val brandPress: TreeColor,
    /** `--tree-color-brand-soft-hover` — derived by the library from the semantic layer. Read it; never set it. */
    public val brandSoftHover: TreeColor,
    /** `--tree-color-brand-soft-press` — derived by the library from the semantic layer. Read it; never set it. */
    public val brandSoftPress: TreeColor,
    /** `--tree-color-brand-on-soft` — derived by the library from the semantic layer. Read it; never set it. */
    public val brandOnSoft: TreeColor,
    /** `--tree-color-brand-on-soft-hover` — derived by the library from the semantic layer. Read it; never set it. */
    public val brandOnSoftHover: TreeColor,
    /** `--tree-color-brand-on-soft-press` — derived by the library from the semantic layer. Read it; never set it. */
    public val brandOnSoftPress: TreeColor,
    /** `--tree-color-accent-press` — derived by the library from the semantic layer. Read it; never set it. */
    public val accentPress: TreeColor,
    /** `--tree-color-accent-soft-hover` — derived by the library from the semantic layer. Read it; never set it. */
    public val accentSoftHover: TreeColor,
    /** `--tree-color-accent-soft-press` — derived by the library from the semantic layer. Read it; never set it. */
    public val accentSoftPress: TreeColor,
    /** `--tree-color-accent-on-soft` — derived by the library from the semantic layer. Read it; never set it. */
    public val accentOnSoft: TreeColor,
    /** `--tree-color-accent-on-soft-hover` — derived by the library from the semantic layer. Read it; never set it. */
    public val accentOnSoftHover: TreeColor,
    /** `--tree-color-accent-on-soft-press` — derived by the library from the semantic layer. Read it; never set it. */
    public val accentOnSoftPress: TreeColor,
    /** `--tree-color-status-success-hover` — derived by the library from the semantic layer. Read it; never set it. */
    public val statusSuccessHover: TreeColor,
    /** `--tree-color-status-success-press` — derived by the library from the semantic layer. Read it; never set it. */
    public val statusSuccessPress: TreeColor,
    /** `--tree-color-status-success-soft` — derived by the library from the semantic layer. Read it; never set it. */
    public val statusSuccessSoft: TreeColor,
    /** `--tree-color-status-success-soft-hover` — derived by the library from the semantic layer. Read it; never set it. */
    public val statusSuccessSoftHover: TreeColor,
    /** `--tree-color-status-success-border` — derived by the library from the semantic layer. Read it; never set it. */
    public val statusSuccessBorder: TreeColor,
    /** `--tree-color-status-success-contrast` — derived by the library from the semantic layer. Read it; never set it. */
    public val statusSuccessContrast: TreeColor,
    /** `--tree-color-status-success-on-soft` — derived by the library from the semantic layer. Read it; never set it. */
    public val statusSuccessOnSoft: TreeColor,
    /** `--tree-color-status-success-on-soft-hover` — derived by the library from the semantic layer. Read it; never set it. */
    public val statusSuccessOnSoftHover: TreeColor,
    /** `--tree-color-status-warning-hover` — derived by the library from the semantic layer. Read it; never set it. */
    public val statusWarningHover: TreeColor,
    /** `--tree-color-status-warning-press` — derived by the library from the semantic layer. Read it; never set it. */
    public val statusWarningPress: TreeColor,
    /** `--tree-color-status-warning-soft` — derived by the library from the semantic layer. Read it; never set it. */
    public val statusWarningSoft: TreeColor,
    /** `--tree-color-status-warning-soft-hover` — derived by the library from the semantic layer. Read it; never set it. */
    public val statusWarningSoftHover: TreeColor,
    /** `--tree-color-status-warning-border` — derived by the library from the semantic layer. Read it; never set it. */
    public val statusWarningBorder: TreeColor,
    /** `--tree-color-status-warning-contrast` — derived by the library from the semantic layer. Read it; never set it. */
    public val statusWarningContrast: TreeColor,
    /** `--tree-color-status-warning-on-soft` — derived by the library from the semantic layer. Read it; never set it. */
    public val statusWarningOnSoft: TreeColor,
    /** `--tree-color-status-warning-on-soft-hover` — derived by the library from the semantic layer. Read it; never set it. */
    public val statusWarningOnSoftHover: TreeColor,
    /** `--tree-color-status-error-hover` — derived by the library from the semantic layer. Read it; never set it. */
    public val statusErrorHover: TreeColor,
    /** `--tree-color-status-error-press` — derived by the library from the semantic layer. Read it; never set it. */
    public val statusErrorPress: TreeColor,
    /** `--tree-color-status-error-soft` — derived by the library from the semantic layer. Read it; never set it. */
    public val statusErrorSoft: TreeColor,
    /** `--tree-color-status-error-soft-hover` — derived by the library from the semantic layer. Read it; never set it. */
    public val statusErrorSoftHover: TreeColor,
    /** `--tree-color-status-error-border` — derived by the library from the semantic layer. Read it; never set it. */
    public val statusErrorBorder: TreeColor,
    /** `--tree-color-status-error-contrast` — derived by the library from the semantic layer. Read it; never set it. */
    public val statusErrorContrast: TreeColor,
    /** `--tree-color-status-error-on-soft` — derived by the library from the semantic layer. Read it; never set it. */
    public val statusErrorOnSoft: TreeColor,
    /** `--tree-color-status-error-on-soft-hover` — derived by the library from the semantic layer. Read it; never set it. */
    public val statusErrorOnSoftHover: TreeColor,
    /** `--tree-color-status-info-hover` — derived by the library from the semantic layer. Read it; never set it. */
    public val statusInfoHover: TreeColor,
    /** `--tree-color-status-info-press` — derived by the library from the semantic layer. Read it; never set it. */
    public val statusInfoPress: TreeColor,
    /** `--tree-color-status-info-soft` — derived by the library from the semantic layer. Read it; never set it. */
    public val statusInfoSoft: TreeColor,
    /** `--tree-color-status-info-soft-hover` — derived by the library from the semantic layer. Read it; never set it. */
    public val statusInfoSoftHover: TreeColor,
    /** `--tree-color-status-info-border` — derived by the library from the semantic layer. Read it; never set it. */
    public val statusInfoBorder: TreeColor,
    /** `--tree-color-status-info-contrast` — derived by the library from the semantic layer. Read it; never set it. */
    public val statusInfoContrast: TreeColor,
    /** `--tree-color-status-info-on-soft` — derived by the library from the semantic layer. Read it; never set it. */
    public val statusInfoOnSoft: TreeColor,
    /** `--tree-color-status-info-on-soft-hover` — derived by the library from the semantic layer. Read it; never set it. */
    public val statusInfoOnSoftHover: TreeColor,
    /** `--tree-color-state-hover-bg` — derived by the library from the semantic layer. Read it; never set it. */
    public val stateHoverBg: TreeColor,
    /** `--tree-color-state-press-bg` — derived by the library from the semantic layer. Read it; never set it. */
    public val statePressBg: TreeColor,
    /** `--tree-color-state-selected-bg` — derived by the library from the semantic layer. Read it; never set it. */
    public val stateSelectedBg: TreeColor,
    /** `--tree-color-state-selected-fg` — derived by the library from the semantic layer. Read it; never set it. */
    public val stateSelectedFg: TreeColor,
    /** `--tree-color-state-selected-border` — derived by the library from the semantic layer. Read it; never set it. */
    public val stateSelectedBorder: TreeColor,
    /** `--tree-color-state-disabled-bg` — derived by the library from the semantic layer. Read it; never set it. */
    public val stateDisabledBg: TreeColor,
    /** `--tree-color-state-disabled-fg` — derived by the library from the semantic layer. Read it; never set it. */
    public val stateDisabledFg: TreeColor,
    /** `--tree-color-state-disabled-border` — derived by the library from the semantic layer. Read it; never set it. */
    public val stateDisabledBorder: TreeColor,
    /** `--tree-shadow-xs` — layers in paint order, colour already composited over the theme’s umbra. */
    public val shadowXs: List<TreeShadowLayer>,
    /** `--tree-shadow-sm` — layers in paint order, colour already composited over the theme’s umbra. */
    public val shadowSm: List<TreeShadowLayer>,
    /** `--tree-shadow-md` — layers in paint order, colour already composited over the theme’s umbra. */
    public val shadowMd: List<TreeShadowLayer>,
    /** `--tree-shadow-lg` — layers in paint order, colour already composited over the theme’s umbra. */
    public val shadowLg: List<TreeShadowLayer>,
    /** `--tree-shadow-xl` — layers in paint order, colour already composited over the theme’s umbra. */
    public val shadowXl: List<TreeShadowLayer>,
    /** `--tree-shadow-accent` — layers in paint order, colour already composited over the theme’s umbra. */
    public val shadowAccent: List<TreeShadowLayer>,
    /** `--tree-gradient-brand` */
    public val gradientBrand: TreeGradient,
)

/**
 * The colour axis for an action surface, orthogonal to its variant.
 *
 * The variant decides the SHAPE — filled, outlined, quiet, tinted — and the
 * tone decides which colour set that shape paints with. Splitting them is what
 * makes a quiet destructive action expressible: a single `danger` variant could
 * only ever be a filled red button.
 */
public enum class TreeTone {
    /** The page's own ink rather than a hue — an action that makes no colour claim. */
    Neutral,
    /** The product's primary action. The default when no tone is set. */
    Brand,
    /** The secondary brand accent: branded, without competing with the primary action. */
    Accent,
    /** A confirming action, or one whose outcome is a success state. */
    Success,
    /** An action that warrants a second look before it is taken. */
    Warning,
    /** A destructive action. It composes with every variant, so a destructive action can also be a quiet one. */
    Danger,
    /** An advisory action in a neutral, informational context. */
    Info,
}

/** One tone resolved against one palette. */
public data class TreeToneColors(
    /** The tone’s solid fill, and its ink on the quiet variants. */
    public val accent: TreeColor,
    /** The tone’s solid fill, and its ink on the quiet variants. */
    public val accentHover: TreeColor,
    /** The tone’s solid fill, and its ink on the quiet variants. */
    public val accentPress: TreeColor,
    /** The tone’s tint, which the `soft` variant fills with. */
    public val accentSoft: TreeColor,
    /** The tone’s tint, which the `soft` variant fills with. */
    public val accentSoftHover: TreeColor,
    /** The tone’s tint, which the `soft` variant fills with. */
    public val accentSoftPress: TreeColor,
    /** Ink that clears AA on the tint. It deepens as the tint deepens, because a tint has only so much headroom. */
    public val accentOnSoft: TreeColor,
    /** The tone’s solid fill, and its ink on the quiet variants. */
    public val accentOnSoftHover: TreeColor,
    /** The tone’s solid fill, and its ink on the quiet variants. */
    public val accentOnSoftPress: TreeColor,
    /** Ink that clears AA on the solid fill. Computed per theme — never `text.inverse`. */
    public val accentContrast: TreeColor,
)

/**
 * This palette’s colours for one tone.
 *
 * Exhaustive over `TreeTone` with no `else` branch, so adding a tone to the
 * contract fails this file to compile rather than silently painting a default.
 */
public fun TreePalette.tone(tone: TreeTone): TreeToneColors =
    when (tone) {
        TreeTone.Neutral -> TreeToneColors(
            accent = textPrimary,
            accentHover = textPrimary,
            accentPress = textPrimary,
            accentSoft = bgSubtle,
            accentSoftHover = stateHoverBg,
            accentSoftPress = statePressBg,
            accentOnSoft = textPrimary,
            accentOnSoftHover = textPrimary,
            accentOnSoftPress = textPrimary,
            accentContrast = textInverse,
        )
        TreeTone.Brand -> TreeToneColors(
            accent = brandPrimary,
            accentHover = brandHover,
            accentPress = brandPress,
            accentSoft = brandSoft,
            accentSoftHover = brandSoftHover,
            accentSoftPress = brandSoftPress,
            accentOnSoft = brandOnSoft,
            accentOnSoftHover = brandOnSoftHover,
            accentOnSoftPress = brandOnSoftPress,
            accentContrast = brandContrast,
        )
        TreeTone.Accent -> TreeToneColors(
            accent = accentPrimary,
            accentHover = accentHover,
            accentPress = accentPress,
            accentSoft = accentSoft,
            accentSoftHover = accentSoftHover,
            accentSoftPress = accentSoftPress,
            accentOnSoft = accentOnSoft,
            accentOnSoftHover = accentOnSoftHover,
            accentOnSoftPress = accentOnSoftPress,
            accentContrast = accentContrast,
        )
        TreeTone.Success -> TreeToneColors(
            accent = statusSuccess,
            accentHover = statusSuccessHover,
            accentPress = statusSuccessPress,
            accentSoft = statusSuccessSoft,
            accentSoftHover = statusSuccessSoftHover,
            accentSoftPress = statusSuccessSoftHover,
            accentOnSoft = statusSuccessOnSoft,
            accentOnSoftHover = statusSuccessOnSoftHover,
            accentOnSoftPress = statusSuccessOnSoftHover,
            accentContrast = statusSuccessContrast,
        )
        TreeTone.Warning -> TreeToneColors(
            accent = statusWarning,
            accentHover = statusWarningHover,
            accentPress = statusWarningPress,
            accentSoft = statusWarningSoft,
            accentSoftHover = statusWarningSoftHover,
            accentSoftPress = statusWarningSoftHover,
            accentOnSoft = statusWarningOnSoft,
            accentOnSoftHover = statusWarningOnSoftHover,
            accentOnSoftPress = statusWarningOnSoftHover,
            accentContrast = statusWarningContrast,
        )
        TreeTone.Danger -> TreeToneColors(
            accent = statusError,
            accentHover = statusErrorHover,
            accentPress = statusErrorPress,
            accentSoft = statusErrorSoft,
            accentSoftHover = statusErrorSoftHover,
            accentSoftPress = statusErrorSoftHover,
            accentOnSoft = statusErrorOnSoft,
            accentOnSoftHover = statusErrorOnSoftHover,
            accentOnSoftPress = statusErrorOnSoftHover,
            accentContrast = statusErrorContrast,
        )
        TreeTone.Info -> TreeToneColors(
            accent = statusInfo,
            accentHover = statusInfoHover,
            accentPress = statusInfoPress,
            accentSoft = statusInfoSoft,
            accentSoftHover = statusInfoSoftHover,
            accentSoftPress = statusInfoSoftHover,
            accentOnSoft = statusInfoOnSoft,
            accentOnSoftHover = statusInfoOnSoftHover,
            accentOnSoftPress = statusInfoOnSoftHover,
            accentContrast = statusInfoContrast,
        )
    }

/**
 * One badge tone resolved against one palette, for one variant.
 *
 * A fill and an edge may be absent — a ghost badge has neither. The ink never
 * is: a badge whose label cannot be read is not a badge.
 */
public data class TreeBadgeColors(
    /** Fill, or `null` for none. */
    public val background: TreeColor?,
    /** Ink. Always present. */
    public val text: TreeColor,
    /** Edge, or `null` for none. Only `Outline` draws one. */
    public val border: TreeColor?,
)

/**
 * This palette's colours for one badge tone and variant.
 *
 * Exhaustive over both vocabularies with no `else` branch, so adding a tone or
 * a variant fails this file to compile rather than silently painting a default.
 */
public fun TreePalette.badgeTone(tone: TreeBadgeTone, variant: TreeVariant): TreeBadgeColors =
    when (tone) {
        TreeBadgeTone.Neutral ->
            when (variant) {
                TreeVariant.Solid -> TreeBadgeColors(
                    background = brandPrimary,
                    text = brandContrast,
                    border = null,
                )
                TreeVariant.Outline -> TreeBadgeColors(
                    background = bgSurface,
                    text = textPrimary,
                    border = borderDefault,
                )
                TreeVariant.Ghost -> TreeBadgeColors(
                    background = null,
                    text = textMuted,
                    border = null,
                )
                TreeVariant.Soft -> TreeBadgeColors(
                    background = brandSoft,
                    text = brandOnSoft,
                    border = null,
                )
            }
        TreeBadgeTone.Success ->
            when (variant) {
                TreeVariant.Solid -> TreeBadgeColors(
                    background = statusSuccess,
                    text = brandContrast,
                    border = null,
                )
                TreeVariant.Outline -> TreeBadgeColors(
                    background = bgSurface,
                    text = statusSuccess,
                    border = statusSuccessBorder,
                )
                TreeVariant.Ghost -> TreeBadgeColors(
                    background = null,
                    text = statusSuccess,
                    border = null,
                )
                TreeVariant.Soft -> TreeBadgeColors(
                    background = statusSuccessSoft,
                    text = statusSuccessOnSoft,
                    border = null,
                )
            }
        TreeBadgeTone.Warning ->
            when (variant) {
                TreeVariant.Solid -> TreeBadgeColors(
                    background = statusWarning,
                    text = brandContrast,
                    border = null,
                )
                TreeVariant.Outline -> TreeBadgeColors(
                    background = bgSurface,
                    text = statusWarning,
                    border = statusWarningBorder,
                )
                TreeVariant.Ghost -> TreeBadgeColors(
                    background = null,
                    text = statusWarning,
                    border = null,
                )
                TreeVariant.Soft -> TreeBadgeColors(
                    background = statusWarningSoft,
                    text = statusWarningOnSoft,
                    border = null,
                )
            }
        TreeBadgeTone.Danger ->
            when (variant) {
                TreeVariant.Solid -> TreeBadgeColors(
                    background = statusError,
                    text = brandContrast,
                    border = null,
                )
                TreeVariant.Outline -> TreeBadgeColors(
                    background = bgSurface,
                    text = statusError,
                    border = statusErrorBorder,
                )
                TreeVariant.Ghost -> TreeBadgeColors(
                    background = null,
                    text = statusError,
                    border = null,
                )
                TreeVariant.Soft -> TreeBadgeColors(
                    background = statusErrorSoft,
                    text = statusErrorOnSoft,
                    border = null,
                )
            }
        TreeBadgeTone.Info ->
            when (variant) {
                TreeVariant.Solid -> TreeBadgeColors(
                    background = statusInfo,
                    text = brandContrast,
                    border = null,
                )
                TreeVariant.Outline -> TreeBadgeColors(
                    background = bgSurface,
                    text = statusInfo,
                    border = statusInfoBorder,
                )
                TreeVariant.Ghost -> TreeBadgeColors(
                    background = null,
                    text = statusInfo,
                    border = null,
                )
                TreeVariant.Soft -> TreeBadgeColors(
                    background = statusInfoSoft,
                    text = statusInfoOnSoft,
                    border = null,
                )
            }
    }

/** The two themes TreeUI ships. A product may build its own `TreePalette` instead. */
public object TreePalettes {
    public val Light: TreePalette = TreePalette(
        mode = TreeColorMode.Light,
        bgPrimary = TreeColor(246, 248, 250, 1.0f),
        bgSurface = TreeColor(255, 255, 255, 1.0f),
        bgSubtle = TreeColor(239, 242, 245, 1.0f),
        borderDefault = TreeColor(208, 215, 222, 1.0f),
        borderStrong = TreeColor(175, 184, 193, 1.0f),
        textPrimary = TreeColor(31, 35, 40, 1.0f),
        textMuted = TreeColor(89, 99, 110, 1.0f),
        textInverse = TreeColor(255, 255, 255, 1.0f),
        shadowRgb = TreeColor(15, 23, 42, 1.0f),
        brandPrimary = TreeColor(9, 105, 218, 1.0f),
        brandHover = TreeColor(5, 80, 174, 1.0f),
        brandSoft = TreeColor(221, 244, 255, 1.0f),
        brandContrast = TreeColor(255, 255, 255, 1.0f),
        accentPrimary = TreeColor(121, 77, 203, 1.0f),
        accentHover = TreeColor(99, 63, 166, 1.0f),
        accentSoft = TreeColor(239, 234, 249, 1.0f),
        accentContrast = TreeColor(255, 255, 255, 1.0f),
        statusSuccess = TreeColor(25, 125, 54, 1.0f),
        statusWarning = TreeColor(148, 99, 0, 1.0f),
        statusError = TreeColor(209, 36, 47, 1.0f),
        statusInfo = TreeColor(9, 105, 218, 1.0f),
        chart1 = TreeColor(42, 120, 214, 1.0f),
        chart2 = TreeColor(18, 133, 92, 1.0f),
        chart3 = TreeColor(138, 97, 0, 1.0f),
        chart4 = TreeColor(0, 131, 0, 1.0f),
        chart5 = TreeColor(74, 58, 167, 1.0f),
        chart6 = TreeColor(227, 73, 72, 1.0f),
        chart7 = TreeColor(196, 88, 127, 1.0f),
        chart8 = TreeColor(235, 104, 52, 1.0f),
        overlay = TreeColor(31, 35, 40, 0.5f),
        focusRing = TreeColor(9, 105, 218, 0.32f),
        borderInteractive = TreeColor(129, 135, 142, 1.0f),
        brandPress = TreeColor(6, 71, 148, 1.0f),
        brandSoftHover = TreeColor(191, 225, 250, 1.0f),
        brandSoftPress = TreeColor(166, 208, 245, 1.0f),
        brandOnSoft = TreeColor(9, 105, 218, 1.0f),
        brandOnSoftHover = TreeColor(8, 90, 187, 1.0f),
        brandOnSoftPress = TreeColor(7, 81, 169, 1.0f),
        accentPress = TreeColor(82, 52, 138, 1.0f),
        accentSoftHover = TreeColor(222, 212, 243, 1.0f),
        accentSoftPress = TreeColor(208, 193, 237, 1.0f),
        accentOnSoft = TreeColor(121, 77, 203, 1.0f),
        accentOnSoftHover = TreeColor(109, 69, 183, 1.0f),
        accentOnSoftPress = TreeColor(99, 63, 165, 1.0f),
        statusSuccessHover = TreeColor(21, 103, 44, 1.0f),
        statusSuccessPress = TreeColor(17, 85, 37, 1.0f),
        statusSuccessSoft = TreeColor(223, 237, 227, 1.0f),
        statusSuccessSoftHover = TreeColor(195, 221, 203, 1.0f),
        statusSuccessBorder = TreeColor(65, 147, 89, 1.0f),
        statusSuccessContrast = TreeColor(255, 255, 255, 1.0f),
        statusSuccessOnSoft = TreeColor(24, 119, 51, 1.0f),
        statusSuccessOnSoftHover = TreeColor(21, 107, 46, 1.0f),
        statusWarningHover = TreeColor(121, 81, 0, 1.0f),
        statusWarningPress = TreeColor(101, 67, 0, 1.0f),
        statusWarningSoft = TreeColor(240, 233, 219, 1.0f),
        statusWarningSoftHover = TreeColor(227, 214, 188, 1.0f),
        statusWarningBorder = TreeColor(166, 126, 44, 1.0f),
        statusWarningContrast = TreeColor(255, 255, 255, 1.0f),
        statusWarningOnSoft = TreeColor(141, 94, 0, 1.0f),
        statusWarningOnSoftHover = TreeColor(127, 85, 0, 1.0f),
        statusErrorHover = TreeColor(171, 30, 39, 1.0f),
        statusErrorPress = TreeColor(142, 24, 32, 1.0f),
        statusErrorSoft = TreeColor(249, 224, 226, 1.0f),
        statusErrorSoftHover = TreeColor(243, 198, 201, 1.0f),
        statusErrorBorder = TreeColor(219, 83, 92, 1.0f),
        statusErrorContrast = TreeColor(255, 255, 255, 1.0f),
        statusErrorOnSoft = TreeColor(199, 34, 45, 1.0f),
        statusErrorOnSoftHover = TreeColor(170, 29, 38, 1.0f),
        statusInfoHover = TreeColor(7, 86, 179, 1.0f),
        statusInfoPress = TreeColor(6, 71, 148, 1.0f),
        statusInfoSoft = TreeColor(221, 234, 250, 1.0f),
        statusInfoSoftHover = TreeColor(191, 216, 246, 1.0f),
        statusInfoBorder = TreeColor(51, 131, 224, 1.0f),
        statusInfoContrast = TreeColor(255, 255, 255, 1.0f),
        statusInfoOnSoft = TreeColor(9, 100, 207, 1.0f),
        statusInfoOnSoftHover = TreeColor(8, 90, 187, 1.0f),
        stateHoverBg = TreeColor(242, 242, 242, 1.0f),
        statePressBg = TreeColor(228, 229, 229, 1.0f),
        stateSelectedBg = TreeColor(221, 244, 255, 1.0f),
        stateSelectedFg = TreeColor(9, 105, 218, 1.0f),
        stateSelectedBorder = TreeColor(9, 105, 218, 1.0f),
        stateDisabledBg = TreeColor(239, 242, 245, 1.0f),
        stateDisabledFg = TreeColor(127, 135, 144, 1.0f),
        stateDisabledBorder = TreeColor(222, 227, 232, 1.0f),
        shadowXs = listOf(TreeShadowLayer(0.0f, 1.0f, 2.0f, 0.0f, TreeColor(15, 23, 42, 0.06f))),
        shadowSm = listOf(TreeShadowLayer(0.0f, 6.0f, 18.0f, 0.0f, TreeColor(15, 23, 42, 0.08f))),
        shadowMd = listOf(TreeShadowLayer(0.0f, 14.0f, 34.0f, 0.0f, TreeColor(15, 23, 42, 0.12f))),
        shadowLg = listOf(TreeShadowLayer(0.0f, 24.0f, 48.0f, -24.0f, TreeColor(15, 23, 42, 0.22f))),
        shadowXl = listOf(TreeShadowLayer(0.0f, 40.0f, 80.0f, -32.0f, TreeColor(15, 23, 42, 0.28f))),
        shadowAccent = listOf(TreeShadowLayer(0.0f, 24.0f, 48.0f, -32.0f, TreeColor(121, 77, 203, 0.6f))),
        gradientBrand = TreeGradient(135.0f, listOf(TreeGradientStop(TreeColor(9, 105, 218, 1.0f), null), TreeGradientStop(TreeColor(5, 80, 174, 1.0f), null))),
    )

    public val Dark: TreePalette = TreePalette(
        mode = TreeColorMode.Dark,
        bgPrimary = TreeColor(28, 33, 40, 1.0f),
        bgSurface = TreeColor(34, 39, 46, 1.0f),
        bgSubtle = TreeColor(45, 51, 59, 1.0f),
        borderDefault = TreeColor(68, 76, 86, 1.0f),
        borderStrong = TreeColor(87, 98, 112, 1.0f),
        textPrimary = TreeColor(173, 186, 199, 1.0f),
        textMuted = TreeColor(149, 163, 178, 1.0f),
        textInverse = TreeColor(28, 33, 40, 1.0f),
        shadowRgb = TreeColor(0, 0, 0, 1.0f),
        brandPrimary = TreeColor(85, 156, 245, 1.0f),
        brandHover = TreeColor(108, 171, 247, 1.0f),
        brandSoft = TreeColor(26, 52, 83, 1.0f),
        brandContrast = TreeColor(10, 26, 47, 1.0f),
        accentPrimary = TreeColor(173, 139, 237, 1.0f),
        accentHover = TreeColor(186, 157, 240, 1.0f),
        accentSoft = TreeColor(51, 46, 74, 1.0f),
        accentContrast = TreeColor(28, 33, 40, 1.0f),
        statusSuccess = TreeColor(91, 174, 94, 1.0f),
        statusWarning = TreeColor(201, 146, 39, 1.0f),
        statusError = TreeColor(245, 118, 110, 1.0f),
        statusInfo = TreeColor(108, 182, 255, 1.0f),
        chart1 = TreeColor(57, 135, 229, 1.0f),
        chart2 = TreeColor(25, 158, 112, 1.0f),
        chart3 = TreeColor(201, 133, 0, 1.0f),
        chart4 = TreeColor(0, 131, 0, 1.0f),
        chart5 = TreeColor(144, 133, 233, 1.0f),
        chart6 = TreeColor(230, 103, 103, 1.0f),
        chart7 = TreeColor(213, 81, 129, 1.0f),
        chart8 = TreeColor(217, 89, 38, 1.0f),
        overlay = TreeColor(13, 17, 23, 0.6f),
        focusRing = TreeColor(85, 156, 245, 0.32f),
        borderInteractive = TreeColor(118, 127, 139, 1.0f),
        brandPress = TreeColor(139, 188, 248, 1.0f),
        brandSoftHover = TreeColor(34, 67, 106, 1.0f),
        brandSoftPress = TreeColor(41, 79, 125, 1.0f),
        brandOnSoft = TreeColor(94, 161, 246, 1.0f),
        brandOnSoftHover = TreeColor(123, 178, 247, 1.0f),
        brandOnSoftPress = TreeColor(153, 196, 249, 1.0f),
        accentPress = TreeColor(199, 176, 243, 1.0f),
        accentSoftHover = TreeColor(68, 59, 97, 1.0f),
        accentSoftPress = TreeColor(83, 70, 116, 1.0f),
        accentOnSoft = TreeColor(173, 139, 237, 1.0f),
        accentOnSoftHover = TreeColor(188, 161, 240, 1.0f),
        accentOnSoftPress = TreeColor(203, 182, 244, 1.0f),
        statusSuccessHover = TreeColor(121, 189, 123, 1.0f),
        statusSuccessPress = TreeColor(143, 200, 146, 1.0f),
        statusSuccessSoft = TreeColor(42, 58, 53, 1.0f),
        statusSuccessSoftHover = TreeColor(49, 74, 59, 1.0f),
        statusSuccessBorder = TreeColor(79, 145, 84, 1.0f),
        statusSuccessContrast = TreeColor(28, 33, 40, 1.0f),
        statusSuccessOnSoft = TreeColor(99, 178, 102, 1.0f),
        statusSuccessOnSoftHover = TreeColor(128, 192, 130, 1.0f),
        statusWarningHover = TreeColor(211, 166, 78, 1.0f),
        statusWarningPress = TreeColor(218, 181, 108, 1.0f),
        statusWarningSoft = TreeColor(57, 54, 45, 1.0f),
        statusWarningSoftHover = TreeColor(77, 67, 44, 1.0f),
        statusWarningBorder = TreeColor(165, 123, 41, 1.0f),
        statusWarningContrast = TreeColor(28, 33, 40, 1.0f),
        statusWarningOnSoft = TreeColor(204, 151, 50, 1.0f),
        statusWarningOnSoftHover = TreeColor(213, 171, 88, 1.0f),
        statusErrorHover = TreeColor(247, 143, 136, 1.0f),
        statusErrorPress = TreeColor(248, 162, 156, 1.0f),
        statusErrorSoft = TreeColor(64, 50, 55, 1.0f),
        statusErrorSoftHover = TreeColor(89, 60, 63, 1.0f),
        statusErrorBorder = TreeColor(200, 101, 96, 1.0f),
        statusErrorContrast = TreeColor(28, 33, 40, 1.0f),
        statusErrorOnSoft = TreeColor(246, 125, 117, 1.0f),
        statusErrorOnSoftHover = TreeColor(247, 149, 143, 1.0f),
        statusInfoHover = TreeColor(134, 195, 255, 1.0f),
        statusInfoPress = TreeColor(155, 205, 255, 1.0f),
        statusInfoSoft = TreeColor(44, 59, 75, 1.0f),
        statusInfoSoftHover = TreeColor(53, 76, 100, 1.0f),
        statusInfoBorder = TreeColor(86, 139, 192, 1.0f),
        statusInfoContrast = TreeColor(28, 33, 40, 1.0f),
        statusInfoOnSoft = TreeColor(108, 182, 255, 1.0f),
        statusInfoOnSoftHover = TreeColor(129, 192, 255, 1.0f),
        stateHoverBg = TreeColor(42, 48, 55, 1.0f),
        statePressBg = TreeColor(51, 57, 64, 1.0f),
        stateSelectedBg = TreeColor(26, 52, 83, 1.0f),
        stateSelectedFg = TreeColor(94, 161, 246, 1.0f),
        stateSelectedBorder = TreeColor(85, 156, 245, 1.0f),
        stateDisabledBg = TreeColor(45, 51, 59, 1.0f),
        stateDisabledFg = TreeColor(118, 129, 142, 1.0f),
        stateDisabledBorder = TreeColor(58, 65, 74, 1.0f),
        shadowXs = listOf(TreeShadowLayer(0.0f, 1.0f, 2.0f, 0.0f, TreeColor(0, 0, 0, 0.06f))),
        shadowSm = listOf(TreeShadowLayer(0.0f, 6.0f, 18.0f, 0.0f, TreeColor(0, 0, 0, 0.08f))),
        shadowMd = listOf(TreeShadowLayer(0.0f, 14.0f, 34.0f, 0.0f, TreeColor(0, 0, 0, 0.12f))),
        shadowLg = listOf(TreeShadowLayer(0.0f, 24.0f, 48.0f, -24.0f, TreeColor(0, 0, 0, 0.22f))),
        shadowXl = listOf(TreeShadowLayer(0.0f, 40.0f, 80.0f, -32.0f, TreeColor(0, 0, 0, 0.28f))),
        shadowAccent = listOf(TreeShadowLayer(0.0f, 24.0f, 48.0f, -32.0f, TreeColor(173, 139, 237, 0.6f))),
        gradientBrand = TreeGradient(135.0f, listOf(TreeGradientStop(TreeColor(85, 156, 245, 1.0f), null), TreeGradientStop(TreeColor(108, 171, 247, 1.0f), null))),
    )
}
