// Regenerates the self-hosted webfonts in assets/fonts/.
//
// TreeUI pins Google Sans Flex and Google Sans Code (both SIL OFL 1.1) as local
// assets so Storybook, CI screenshot runs, and offline development never depend
// on a runtime fetch to fonts.googleapis.com.
//
// Usage: node scripts/fonts/fetch.mjs

import { Buffer } from 'node:buffer';
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const OUT_DIR = fileURLToPath(new URL('../../assets/fonts/', import.meta.url));

// A modern UA is required or the API serves legacy `ttf` instead of `woff2`.
const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

// Only the subsets the docs and examples actually render.
const SUBSETS = new Set(['latin', 'latin-ext']);

const FAMILIES = [
  {
    slug: 'google-sans-flex',
    // Flex exposes `slnt`, not `ital`. Requesting `ital` returns HTTP 200 with
    // upright-only faces, so asking for the slant range is what actually yields
    // a slanted face — one variable file spans upright through 10deg.
    css: 'https://fonts.googleapis.com/css2?family=Google+Sans+Flex:slnt,wght@-10..0,400..800&display=swap',
  },
  {
    slug: 'google-sans-code',
    // Code does have real italics, so both styles are fetched.
    css: 'https://fonts.googleapis.com/css2?family=Google+Sans+Code:ital,wght@0,400..800;1,400..800&display=swap',
  },
];

const field = (block, name) =>
  block.match(new RegExp(`${name}:\\s*([^;]+);`))?.[1].trim() ?? null;

async function collect({ slug, css }) {
  const res = await fetch(css, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${slug}: css2 responded ${res.status}`);
  const sheet = await res.text();

  const faces = [];
  const blocks = sheet.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g);

  for (const [, subset, block] of blocks) {
    if (!SUBSETS.has(subset)) continue;

    const style = field(block, 'font-style');
    const italic = style.startsWith('italic');
    const file = `${slug}-${subset}${italic ? '-italic' : ''}.woff2`;
    const url = block.match(/url\((https:\/\/[^)]+)\)/)[1];

    const binary = await fetch(url, { headers: { 'User-Agent': UA } });
    if (!binary.ok) throw new Error(`${file}: download responded ${binary.status}`);
    const bytes = Buffer.from(await binary.arrayBuffer());
    await writeFile(new URL(file, `file://${OUT_DIR}`), bytes);

    faces.push({
      file,
      subset,
      italic,
      bytes: bytes.length,
      family: field(block, 'font-family'),
      style,
      weight: field(block, 'font-weight'),
      stretch: field(block, 'font-stretch'),
      range: field(block, 'unicode-range'),
    });
  }

  if (faces.length === 0) throw new Error(`${slug}: no matching subsets in css2 response`);

  // css2 returns subsets in an unstable order; sort so regenerating produces a
  // clean diff rather than a reshuffle.
  faces.sort(
    (a, b) => Number(a.italic) - Number(b.italic) || a.subset.localeCompare(b.subset),
  );
  return faces;
}

function renderSheet(faces) {
  const header = [
    '/* TreeUI self-hosted webfonts.',
    ' *',
    ' * Google Sans Flex and Google Sans Code, SIL Open Font License 1.1.',
    ' * See OFL-google-sans-flex.txt and OFL-google-sans-code.txt in this directory.',
    ' *',
    ' * Generated by scripts/fonts/fetch.mjs — edit that script, not this file.',
    ' * Subsets: latin + latin-ext only.',
    ' *',
    ' * Flex carries a `slnt` axis rather than a true italic, so a single face covers',
    ' * upright through slanted via `font-style: oblique 0deg 10deg`.',
    ' */',
    '',
  ];

  const rules = faces.map((f) =>
    [
      '@font-face {',
      `  font-family: ${f.family};`,
      `  font-style: ${f.style};`,
      `  font-weight: ${f.weight};`,
      ...(f.stretch ? [`  font-stretch: ${f.stretch};`] : []),
      '  font-display: swap;',
      `  src: url('./${f.file}') format('woff2');`,
      `  unicode-range: ${f.range};`,
      '}',
      '',
    ].join('\n'),
  );

  return [...header, ...rules].join('\n');
}

await mkdir(OUT_DIR, { recursive: true });

const faces = (await Promise.all(FAMILIES.map(collect))).flat();
await writeFile(new URL('fonts.css', `file://${OUT_DIR}`), renderSheet(faces));

const total = faces.reduce((sum, f) => sum + f.bytes, 0);
for (const f of faces) {
  console.log(`${f.file.padEnd(44)} ${String(Math.round(f.bytes / 1024)).padStart(4)} KB`);
}
console.log(`\n${faces.length} faces, ${Math.round(total / 1024)} KB total → assets/fonts/`);
