import type { App, Plugin } from 'vue';
import {
  TAccordion,
  TAccordionItem,
  TAlert,
  TBadge,
  TBreadcrumb,
  TBreadcrumbItem,
  TButton,
  TCard,
  TCheckbox,
  TContextMenu,
  TDatePicker,
  TDrawer,
  TDropdown,
  TFormField,
  TInput,
  TModal,
  TPagination,
  TPopover,
  TProgress,
  TRadio,
  TRadioGroup,
  TSelect,
  TSkeleton,
  TSpinner,
  TSwitch,
  TTextarea,
  TTabs,
  TTabList,
  TTab,
  TTabPanel,
  TToast,
  TToastProvider,
  TTooltip,
  TAvatar,
  TDivider,
  TTable,
  TTag,
  TPricing,
  TPricingCard,
  TMarkdownEditor,
} from './components';

const components = {
  TAccordion,
  TAccordionItem,
  TAlert,
  TBadge,
  TBreadcrumb,
  TBreadcrumbItem,
  TButton,
  TCard,
  TCheckbox,
  TContextMenu,
  TDatePicker,
  TDrawer,
  TDropdown,
  TFormField,
  TInput,
  TModal,
  TRadio,
  TRadioGroup,
  TSelect,
  TSkeleton,
  TSpinner,
  TSwitch,
  TTextarea,
  TTabs,
  TTabList,
  TTab,
  TTabPanel,
  TToast,
  TToastProvider,
  TPagination,
  TPopover,
  TProgress,
  TTooltip,
  TAvatar,
  TDivider,
  TTable,
  TTag,
  TPricing,
  TPricingCard,
  TMarkdownEditor,
  TreeAccordion: TAccordion,
  TreeAccordionItem: TAccordionItem,
  TreeAlert: TAlert,
  TreeBadge: TBadge,
  TreeBreadcrumb: TBreadcrumb,
  TreeBreadcrumbItem: TBreadcrumbItem,
  TreeButton: TButton,
  TreeCard: TCard,
  TreeCheckbox: TCheckbox,
  TreeContextMenu: TContextMenu,
  TreeDatePicker: TDatePicker,
  TreeDrawer: TDrawer,
  TreeDropdown: TDropdown,
  TreeRadio: TRadio,
  TreeRadioGroup: TRadioGroup,
  TreeSelect: TSelect,
  TreeSkeleton: TSkeleton,
  TreeInput: TInput,
  TreeTextarea: TTextarea,
  TreeModal: TModal,
  TreePagination: TPagination,
  TreePopover: TPopover,
  TreeSpinner: TSpinner,
  TreeFormField: TFormField,
  TreeProgress: TProgress,
  TreeSwitch: TSwitch,
  TreeTabs: TTabs,
  TreeTabList: TTabList,
  TreeTab: TTab,
  TreeTabPanel: TTabPanel,
  TreeToast: TToast,
  TreeToastProvider: TToastProvider,
  TreeTooltip: TTooltip,
  TreeAvatar: TAvatar,
  TreeDivider: TDivider,
  TreeTable: TTable,
  TreeTag: TTag,
  TreePricing: TPricing,
  TreePricingCard: TPricingCard,
  TreeMarkdownEditor: TMarkdownEditor,
};

export const TreeUIPlugin: Plugin = {
  install(app: App) {
    Object.entries(components).forEach(([name, component]) => {
      app.component(name, component);
    });
  },
};

export const install = TreeUIPlugin.install;
