import type { App, Plugin } from 'vue';
import {
  TAccordion,
  TAccordionItem,
  TAlert,
  TBadge,
  TBreadcrumb,
  TBreadcrumbItem,
  TButton,
  TCard,
  TCheckbox,
  TCombobox,
  TConfirmDialog,
  TContainer,
  TContextMenu,
  TDatePicker,
  TDrawer,
  TDropdown,
  TEmptyState,
  TFileUpload,
  TFormField,
  TGrid,
  TAppBar,
  TInput,
  TNavMenu,
  TNavbar,
  TMultiSelect,
  TModal,
  TNumberInput,
  TPagination,
  TPopover,
  TProgress,
  TRadio,
  TRadioGroup,
  TSelectableList,
  TSelect,
  TSidebar,
  TSkeleton,
  TSpinner,
  TStack,
  TStat,
  TStepper,
  TSteps,
  TSwitch,
  TTextarea,
  TTabs,
  TTabList,
  TTab,
  TTabPanel,
  TToggleGroup,
  TToast,
  TToastProvider,
  TTooltip,
  TAvatar,
  TDivider,
  TTable,
  TTag,
  TTreeView,
  TTimeline,
  TPricing,
  TPricingCard,
  TMarkdownEditor,
} from './components';

const components = {
  TAccordion,
  TAccordionItem,
  TAlert,
  TBadge,
  TBreadcrumb,
  TBreadcrumbItem,
  TButton,
  TCard,
  TCheckbox,
  TCombobox,
  TConfirmDialog,
  TContainer,
  TContextMenu,
  TDatePicker,
  TDrawer,
  TDropdown,
  TEmptyState,
  TFileUpload,
  TFormField,
  TGrid,
  TAppBar,
  TInput,
  TNavMenu,
  TNavbar,
  TMultiSelect,
  TModal,
  TNumberInput,
  TRadio,
  TRadioGroup,
  TSelectableList,
  TSelect,
  TSidebar,
  TSkeleton,
  TSpinner,
  TStack,
  TStat,
  TStepper,
  TSteps,
  TSwitch,
  TTextarea,
  TTabs,
  TTabList,
  TTab,
  TTabPanel,
  TToggleGroup,
  TToast,
  TToastProvider,
  TPagination,
  TPopover,
  TProgress,
  TTooltip,
  TAvatar,
  TDivider,
  TTable,
  TTag,
  TTreeView,
  TTimeline,
  TPricing,
  TPricingCard,
  TMarkdownEditor,
  TreeAccordion: TAccordion,
  TreeAccordionItem: TAccordionItem,
  TreeAlert: TAlert,
  TreeBadge: TBadge,
  TreeBreadcrumb: TBreadcrumb,
  TreeBreadcrumbItem: TBreadcrumbItem,
  TreeButton: TButton,
  TreeCard: TCard,
  TreeCheckbox: TCheckbox,
  TreeCombobox: TCombobox,
  TreeConfirmDialog: TConfirmDialog,
  TreeContainer: TContainer,
  TreeContextMenu: TContextMenu,
  TreeDatePicker: TDatePicker,
  TreeDrawer: TDrawer,
  TreeDropdown: TDropdown,
  TreeEmptyState: TEmptyState,
  TreeFileUpload: TFileUpload,
  TreeGrid: TGrid,
  TreeNavbar: TNavbar,
  TreeAppBar: TNavbar,
  TreeNavMenu: TNavMenu,
  TreeMultiSelect: TMultiSelect,
  TreeRadio: TRadio,
  TreeRadioGroup: TRadioGroup,
  TreeSelect: TSelect,
  TreeSkeleton: TSkeleton,
  TreeSidebar: TSidebar,
  TreeInput: TInput,
  TreeNumberInput: TNumberInput,
  TreeSelectableList: TSelectableList,
  TreeStack: TStack,
  TreeTreeView: TTreeView,
  TreeSteps: TSteps,
  TreeStepper: TStepper,
  TreeToggleGroup: TToggleGroup,
  TreeTextarea: TTextarea,
  TreeModal: TModal,
  TreePagination: TPagination,
  TreePopover: TPopover,
  TreeSpinner: TSpinner,
  TreeFormField: TFormField,
  TreeProgress: TProgress,
  TreeStat: TStat,
  TreeSwitch: TSwitch,
  TreeTabs: TTabs,
  TreeTabList: TTabList,
  TreeTab: TTab,
  TreeTabPanel: TTabPanel,
  TreeToast: TToast,
  TreeToastProvider: TToastProvider,
  TreeTooltip: TTooltip,
  TreeAvatar: TAvatar,
  TreeDivider: TDivider,
  TreeTable: TTable,
  TreeTag: TTag,
  TreeTimeline: TTimeline,
  TreePricing: TPricing,
  TreePricingCard: TPricingCard,
  TreeMarkdownEditor: TMarkdownEditor,
};

export const TreeUIPlugin: Plugin = {
  install(app: App) {
    Object.entries(components).forEach(([name, component]) => {
      app.component(name, component);
    });
  },
};

export const install = TreeUIPlugin.install;
